### ISSUE TITLE
.woff or .woff2 type font 

### ISSUE THREAD

**Issue by NateLing** [adobe-fonts/source-han-sans#113]
Can you make .woff or .woff2 type font ?

**Comment by kenlunde** [comment]
Given that this repository is already on the extremely huge side, I will label this as [Do It Yourself](https://people.mozilla.org/~jkew/woff/) for now.

**Comment by ShikiSuen** [comment]
Why not grab them from Adobe's web-font hosting site?

**Comment by kenlunde** [comment]
@ShikiSuen: How can @NateLing do this? As far as I am aware, Typekit is not serving woffs or woff2s. It's a proprietary technology that we've been cooking up for a few years. You can read more about it [here](http://blog.typekit.com/2015/06/15/announcing-east-asian-web-font-support/).

**Comment by ShikiSuen** [comment]
to @kenlunde >
Sorry for my last reply. I should indicate that he could grab such format from other web-font hosting sites.
(some of them may use woff and / or woff2 format.)

**Comment by jungshik** [comment]
@NateLing: You can use Behdad's fonttools to produce woff ( https://github.com/behdad/fonttools/). 
You can also use woff2_compress included in woff2 reference implementation. ( https://github.com/google/woff2 )

**Comment by NateLing** [comment]
@jungshik @kenlunde  @ShikiSuen ,ths for your help, I just want to test that how to use the CJK font on web site.CJK font are very big(5~10Mb),I want to delete some word form the font file and then make them as woff and so on.

**Comment by jakwings** [comment]
@NateLing You can visit http://justfont.com/ too.

**Comment by DanielRuf** [comment]
Mh, any updates on this?

Is there any recommendable fontface kit for web?

**Comment by kenlunde** [comment]
While it sounds like it doesn't help @NateLing for the reasons described above, have you considered Typekit?

**Comment by DanielRuf** [comment]
@kenlunde actually this would be a solution. Google does not yet support it so we have only Typekit atm? Just want to make sure I know all the options for web eg for selfhosting the font (not sure if Typekit provides the woff/woff2 files for selfhosting or as CDN fallback or when there is no connectivity (possible).

**Comment by ShikiSuen** [comment]
@DanielRuf You have both Typekit and Justfont and you could choose either of them. I recommend using Typekit since it is directly supported by Adobe. However, Source-Han fonts hosted on Typekit are subset OTFs [1][2] which requires a complicate fallback setting and a necessary subscription of multiple subset.

References:
[1] https://twitter.com/ken_lunde/status/704830322999832576
[2] https://github.com/adobe-fonts/source-han-sans/tree/release/SubsetOTF

**Comment by kenlunde** [comment]
The _Source Han Serif_ fonts served by Typekit are the language-specific OTFs with the full glyph set. When we release _Source Han Sans_ Version 2.000 later this year, they will be deployed on Typekit as the language-specific OTFs with the full glyph set.

The reason why the _Source Han Sans_ region-specific subset OTFs were deployed was because there were performance concerns that turned out to be a non-concern, thanks to how well dynamic-augmentation functioned.

**Comment by DanielRuf** [comment]
Thanks for the clarification.

**Comment by ruiming** [comment]
Can I still use the "Source Han Sans" name if I transform the font to woff/woff2 type.

> No Modified Version of the Font Software may use the Reserved Font Name(s) unless explicit written permission is granted by the corresponding Copyright Holder. This restriction only applies to the primary font name as presented to the users.

**Comment by DanielRuf** [comment]
> Can I still use the "Source Han Sans" or "思源黑体" name if I transform the font to woff/woff2 type?
> 
> > No Modified Version of the Font Software may use the Reserved Font Name(s) unless explicit written permission is granted by the corresponding Copyright Holder. This restriction only applies to the primary font name as presented to the users.

This is not a modified version then afaik.
Only if you "fork" or make your very own version.
This is just a conversion.

**Comment by tamcy** [comment]
> Can I still use the "Source Han Sans" or "思源黑体" name if I transform the font to woff/woff2 type?

@ruiming I suggest you to check out the SIL website. It has some [FAQ entries](https://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web#1db14da7) and a [paper ("Web fonts and RFNs")](https://scripts.sil.org/OFL_web_fonts_and_RFNs) that discuss about Reserved Font Names in various web font formats.
