### ISSUE TITLE
Optimize glyphs for regular/normal weights

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-sans#116]
It is no secret that Source Han Sans is a multiple master font. This means that weights between the lightest (ExtraLight) and the heaviest (Heavy) ones are interpolated by computer program. Due to this nature, the normal (regular included) weight may not appear best looking in all cases. Here are some examples:

![shsregular2](https://cloud.githubusercontent.com/assets/959433/8411865/c463b2bc-1eb8-11e5-8847-dc7ce6b61cf6.png)
It is very easy to spot out the inconsistent thickness of the strokes, especially when viewed in smaller sizes (e.g. on my Nexus 5 phone). The listed components appear significantly thinner than they should be:
- the 巳 component in 港
- the 品 component in 軀 and 樞
- the 或 component in 國
- the two 口s in 勸

This is due to how the heaviest weight glyphs are crafted. The designer intentionally reduced the thickness of these components so that the glyphs won't appear too black as a whole, but these reduced thickness are brought backward to the in-between weights, even to those where such an adjustment is not (yet) necessary. This results in the strokes appear to be somewhat "loose", giving an impression that the glyphs aren't carefully optimized.

As normal weight is the daily driver for most use cases (system UI to be one crucial part), I would like to suggest to improve the quality of the glyphs for this weight. What if a fine-tuned regular glyph can be created as an extra reference point / anchor for other interpolated weights? Of course, not all glyphs require such treatment, but some are obviously needed. For example, the "inconsistent vertical line" of 敝 could be an example why this is a good idea:
![shsregular3](https://cloud.githubusercontent.com/assets/959433/8412050/e2a81ec4-1eb9-11e5-99d8-d925a72f4f37.png)

**Comment by davelab6** [comment]
[David Lemon](https://www.linkedin.com/pub/david-lemon/1/212/a95) suggested the CJK interpolation system may be open sourced last year at ATypI ([video](https://www.youtube.com/watch?v=DBz0rVUYNPA&feature=youtu.be&t=16m37s)) but since then nothing about releasing the actual interpolation source files and CJK interpolation system has been announced (that I've seen - maybe I missed something :) 

I think I might be wrong on this, but I believe that one of the reasons for the Adobe Type team's interest in liberating https://github.com/letterror/mutatorMath was that it allows for arbitrary intermediate masters, whereas Adobe's Multiple Master interpolation model only allows for intermediate masters when interpolating along 1 axis. 

It seems to me that the kind of adjustment you're describing would require mutatorMath-style interpolation.

**Comment by kenlunde** [comment]
Given that we're likely to eventually develop a Variable Font version of the _Source Han_ families, and given the number of glyphs, the likelihood of breaking away from straight interpolation is very low, especially if we want to maintain parity between the non–Variable Font releases.
