### ISSUE TITLE
Five characters (U+9FD1-U+9FD5，鿑鿒鿓鿔鿕) in Unicode 8.0 should be added.

### ISSUE THREAD

**Issue by yan321** [adobe-fonts/source-han-sans#121]
U+9FD1 ⿰冫玉
U+9FD2 ⿱艹页
U+9FD3 ⿱艹⾴
U+9FD4 ⿰钅哥
U+9FD5 ⿰鱼丹
![360 20150802123646](https://cloud.githubusercontent.com/assets/11794747/9024746/1dacd942-3913-11e5-8ceb-0763fda36313.png)
http://www.unicode.org/charts/PDF/U4E00.pdf

**Comment by yan321** [comment]
And 𫟷(U+2B7F7) may be also important.

**Comment by kenlunde** [comment]
I will consolidate this with Issue #115, which is the appropriate place for this, and close this one.

Although not shown in that issue, because it is meant for contributors, my own notes already indicate that glyphs for U+9FD1 through U+9FE9, along with one for U+2B7F7, should be added.

These characters are technically beyond the original scope of the fonts, but I plan to include them anyway, mainly to keep the URO complete. U+9FCD through U+9FCF were included because they're included in China's 2013 list of 8,105 hanzi (通用规范汉字表), and U+9FD0 is a Hong Kong SCS character that resulted in a disunification of U+4CA4.

U+9FD6 through U+9FE9 are slated for Unicode Version 9.0, but are stable enough to encode.

**Comment by kenlunde** [comment]
Consolidated with Issue #180.
