### ISSUE TITLE
Is it the same with Noto Sans CJK Fonts?

### ISSUE THREAD

**Issue by laichiaheng** [adobe-fonts/source-han-sans#122]
Are these two fonts the same?

**Comment by kenlunde** [comment]
Yes, in terms of the glyphs, their metrics, Unicode mappings, and features. In other words, the Source Han Sans and Noto Sans CJK typeface families are mechanically identical. I know, because I built the fonts of both families.

They differ only in their names, and the fact that the Noto Sans CJK fonts lack localized menu names.

**Comment by laichiaheng** [comment]
So Source Han Sans is more complete than Noto?

**Comment by kenlunde** [comment]
It depends on your definition of "more complete." Localized menu names are not required, but may make fonts more user-friendly for customers whose native language is that of the target language of the font.
