### ISSUE TITLE
Hangul should using the same with as Chinese characters (Hanja)

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe-fonts/source-han-sans#139]
Many Hangul fonts using the the same with for Hangul and Hanja glyps, but in Source Han Sans they seems a bit proportional. See my screenshot from [3·1독립선언서](https://ko.wikisource.org/wiki/3%C2%B71%EB%8F%85%EB%A6%BD%EC%84%A0%EC%96%B8%EC%84%9C) (Proclamation of Korean Independence).

![Screenshot from Korean Wikisource](http://chuantu.biz/t2/24/1453468883x-1376440248.png)

**Comment by kenlunde** [comment]
While it is true that the glyphs for hangul in many Korean fonts have widths that match the ideographs (hanja), there are also many Korean fonts whose glyphs for hangul have narrower (but still monospaced) widths, meaning that Source Han Sans is no exception. The actual width of the glyphs for hangul, which is 92% of the width for the  ideographs, was set at the discretion of the Korean designer. In other words, this issue is as designed.

**Comment by KrasnayaPloshchad** [comment]
So what if adding `fwid` feature for them?

**Comment by kenlunde** [comment]
Doing so would negatively affect inter-glyph spacing. Keep in mind that typical Korean text makes extensive use of spaces and Western-style punctuation, so unlike typical Japanese and Chinese text, it doesn't need to fit into a grid-like construct. This is the reason why many Korean fonts include glyphs for hangul that have narrower widths than those of ideographs.

Of course, because this is an open source project, you are free to fork it and modify it to suit your needs. Such a change will not be made to the main branch.
