### ISSUE TITLE
Tweaking width metrics of full-width punctuation marks in "palt" table.

### ISSUE THREAD

**Issue by ShikiSuen** [adobe-fonts/source-han-sans#146]
I have to say: even though using Non-TW&HK branches of Source Han Sans (i.e.: using Chinese, Korean, or Japanese version of SHS), the period and the comma looks still terrible:

![image](https://cloud.githubusercontent.com/assets/3164826/13458071/a98d9a66-e028-11e5-94f5-041152c257fe.png)
(The 1st paragraph and the title uses Source Han Sans TypeKit Chinese Simplified, while the 2nd paragraph uses SHS TypeKit Japanese)
source: http://tonaltheorynotes.com/cjktest/

My suggestion is to change what I circled below to 75% or 80% regarding full-width punctuation marks:
![image](https://cloud.githubusercontent.com/assets/3164826/13458128/fb919092-e028-11e5-9f97-bdb389f32196.png)

**Comment by kenlunde** [comment]
Any particular reason why you closed this?

**Comment by ShikiSuen** [comment]
@kenlunde 'cause I think you will reopen it if you think such issue matters. This explanation works for every issue I posted here closed by myself before any reply commented (Unless I explained something else).

**Comment by ShikiSuen** [comment]
@kenlunde Looks like I made over-assumptions regarding what you said in this post:
> https://github.com/adobe-fonts/source-han-sans/issues/100#issuecomment-94993004
> "Feel free to close this issue if you feel doing so is appropriate."

I cross-referenced all my previous issues and have realized what I quote was only related to that issue but not all of my issues. My apologies. I will reopen this issue.

**Comment by pukoh** [comment]
I'm not up to with the chinese font technical lingo, but i think this question belongs here.

The fullstop in other chinese fonts usually take up the same space as a chinese character. (so everything lines up (e.g. tubular numerals) 

is this already possible with the current font set?
i'm using this font in indesign.

**Comment by kenlunde** [comment]
@pukoh: If you are using one of the Chinese fonts from this repository, the full stop and other CJK punctuation are most definitely full-width by default, matching the advance widths of the glyphs for hanzi and other characters used for Chinese. When using InDesign, you need to be careful about which paragraph composer is being used, and especially the paragraph composer's settings. I believe that the default behavior is tuned for Japanese, which may make some glyphs for punctuation half-width in order to follow Japanese line-layout principles.

**Comment by pukoh** [comment]
I tried searching for options to change paragraph composer settings. But not having any luck.

Also tried to look for the fullwidth punctuations in the glyphs window, but there's too many characters!!!

Do you know where the setting is?

**Comment by hfhchan** [comment]
Please see
https://helpx.adobe.com/illustrator/using/formatting-asian-characters.html
and refer to section on *mojikumi*.
2016年4月28日 下午6:50 於 "pu" <notifications@github.com> 寫道：

**Comment by hfhchan** [comment]
Mojikumi (標點擠壓).

As a side note, I wonder why this isn't translated as "Punctuation Compression" or "Adjust Punctuation Width".

**Comment by pukoh** [comment]
So just found this.

To get the CJK tools in indesign, you need to download the 'chinese' version of indesign. 
https://helpx.adobe.com/creative-cloud/help/change-install-language.html

I just did it, UI still in english, but all the CJK tools are now available.

But you might not even need to do this. I just went and changed the Kerning to 0 instead of Metric. And the punctuations have gone to fullwidth.

**Comment by kenlunde** [comment]
@pukoh: You have just discovered why text layout tools such as InDesign have a high learning curve. The options and toggles are there, and it is merely a matter of learning where they are and how to use them.

And yes, the kerning setting of "Metric" will invoke the 'kern' GPOS feature, and if exists (and it does in Source Han Sans), the 'palt' GPOS feature is also invoked, [per the OpenType Specification](https://www.microsoft.com/typography/otspec/features_ko.htm#kern). So, turning that off has the effect that you desire.
