### ISSUE TITLE
When using PDFCreator, loss of all Chinese Fonts.

### ISSUE THREAD

**Issue by SourcePowered** [adobe-fonts/source-han-sans#165]
When using PDFCreator ( http://www.pdfforge.org, PDF version is 1.6 ) to create a PDF doc, loss of all Chinese Fonts.
And I try any other PDF document generator ( Like LibreOffice, PDF version is 1.4 ), Is normal. But if the document contains images, it is still missing all Fonts.

"Loss of all Fonts"'s meaning: All Chinese fonts are blank (except English and numbers).

**Comment by kenlunde** [comment]
This is clearly not a font issue, and I suspect that either 1) PDFCreator doesn't support CJK or CFF-based OpenType fonts; or 2) PDFCreator has an option that must be explicitly turned on in order to enable such support. The referenced website seems to be down, so I cannot check their documentation.
