### ISSUE TITLE
Region-specific Subset OTFs

### ISSUE THREAD

**Issue by yezige** [adobe-fonts/source-han-sans#172]
The second `Taiwan,` should not this be written as `China Taiwan`?

**Comment by LEOYoon-Tsaw** [comment]
This subset is not for the use in mainland China. The name should better be consistent with the convention of the targeted region.

**Comment by showerying** [comment]
hahahah😆
第一天上网？
First time on the web?

**Comment by 126ium** [comment]
This project is not the propaganda of CPC. DON'T involve any political standpoint.

**Comment by yezige** [comment]
@showerying 估计你是第一天
@LEOYoon-Tsaw @126ium There is only ambiguity

**Comment by fei0316** [comment]
I'm actually curious where of the code you are referring to...
To put away all political stuff, this is referring to the culture of the region (the way of writing) instead of an expression of the sovereignty of the place. Also it's easy to cause confusion, as the MOE standard glyph has nothing to do with mainland Chinese government...
You may request the removal of Taiwan region specific subset altogether that way...

**Comment by Vdragon** [comment]
![image](https://cloud.githubusercontent.com/assets/1192163/24753804/554ffdc6-1b06-11e7-9abc-c10b3ea6fde5.png)

<https://www.reddit.com/r/place/hot/#x=980&y=736>

Sorry for stepping in a flame war mOwOm

**Comment by kenlunde** [comment]
If it were up to me, we would not deploy the region-specific subset OTFs at all, because they're not Pan-CJK fonts, and the whole point of the _Source Han_ typefaces is that they're Pan-CJK.

We deployed them for older environments that might not be able to deal with Pan-CJK fonts, or for the limited number of users who don't care about the Pan-CJK functionality. For me, the ideal deployment format is the Super OTC, which packs all of the fonts into a single and easy-to-manage font resource. As soon as our friends at Microsoft release the Windows 10 Creators Update, the Super OTCs will be usable on Windows.
