### ISSUE TITLE
Provide italic western letters

### ISSUE THREAD

**Issue by TitanSnow** [adobe-fonts/source-han-sans#191]
The glyphs of western letters (Latin & Greek) of *Source Han Sans* are from *Source Sans Pro* but differ. It makes typesetting CJK and Western mixed texts difficult especially when italic western characters are needed. One cannot simply use *Source Sans Pro Italic* because it doesn't match *Source Han Sans*.

How about providing a configuration with italic western letters? The OpenType feature `ital` can be used, or a separate OTF if glyph number limit troubles.

**Comment by kenlunde** [comment]
If we had CIDs to spare, which we don't, I would seriously consider adding italic glyphs.

**Comment by TitanSnow** [comment]
So what about *separate OTF for italic*?

**Comment by kenlunde** [comment]
The short answer: _Don't hold your breath._

The long answer: For this to work as you expect, and because there aren't enough available CIDs, the entire 65,535-glyph glyph set would first need to be duplicated as a separate project, then all of the proportional glyphs that correspond to Western characters would need to be replaced with their [_Source Sans Pro_ Italic](https://github.com/adobe-fonts/source-sans-pro/tree/master/Italic) counterparts, which would also involve selecting appropriate weight instances and applying weight-specific scaling factors (as described on the page 7 of the ReadMe). In other words, it would entail creating a completely different set of fonts whose glyphs are identical to _Source Han Sans_ except for about 1% or so that would be italic.

**Comment by TitanSnow** [comment]
Obviously CJK characters have no italic shape, so there's no need to duplicate them. Just a small OTF contains only western characters that in appropriate weight and have been scaled to be used with *Souce Han Sans*, just like *Source Han Sans Italic Western* or something like so.

**Comment by kenlunde** [comment]
Unfortunately, we have neither the time nor resources to develop such fonts right now. I would rather consider this at the same time we develop the Variable Font version of this family. In addition, using such fonts wouldn't be a very good user experience, because it would require an explicit font change to invoke the italic glyphs.

Related to this, and as a way to provide a better user experience for such fonts, it's unfortunate that CFR (aka [ISO/IEC 14496-28](https://blogs.adobe.com/CCJKType/2013/11/cfr-now-freely-available.html) or [_Composite Font Representation_](https://blogs.adobe.com/CCJKType/2012/05/all-unicode-cfr.html)) objects are not broadly supported outside of [macOS](https://blogs.adobe.com/CCJKType/2012/07/cfr-support-in-mountain-lion.html), because the following snippet could potentially represent the bulk of its definition:

```
<Components>
        <ComponentDef name="SourceHanSansIt"/>
        <LanguagePreferredList>
                <LanguagePreferredComponentDef>
                        <Language string="ja"/>
                        <ComponentDef name="SourceHanSans"/>
                        <Language string="ko"/>
                        <ComponentDef name="SourceHanSansK"/>
                        <Language string="zh-Hans"/>
                        <ComponentDef name="SourceHanSansSC"/>
                        <Language string="zh-Hant"/>
                        <ComponentDef name="SourceHanSansTC"/>
                </LanguagePreferredComponentDef>
        </LanguagePreferredList>
</Components>

```

For now, this will be marked as DIY.

**Comment by frankrolf** [comment]
> In addition, using such fonts wouldn't be a very good user experience, because it would require an explicit font change to invoke the italic glyphs.

Is there no style linking for CJK fonts? That could be a good (and well-established) solution.

**Comment by kenlunde** [comment]
The _Source Han Serif_ family uses style-linking, which is employed for the Regular and Bold weights. We will do the same for this family as part of the Version 2.000 update.
