### ISSUE TITLE
请求发布win10系统商店版本

### ISSUE THREAD

**Issue by findlayfeng** [adobe-fonts/source-han-sans#192]
win10系统17040以后版本可以从商店安装系统字体，我想把思源字体作为系统字体，请求发布win10商店版本  ^_^

**Comment by findlayfeng** [comment]
额，抱歉，我弄错。。。。

**Comment by kenlunde** [comment]
🤨

**Comment by hfhchan** [comment]
This is actually a good suggestion.  If Source Han Sans were distributed through the new Windows 10 App Store Fonts section, that would aid the uptake of Source Han Sans, which is a good thing for China (mainland), Taiwan, Japanese and Korean users.

**Comment by kenlunde** [comment]
Given that Windows 10 is already bloated, the only font I would consider is the [142-font Ultra OTC](https://github.com/adobe-fonts/source-han-super-otc) that includes the three _Source Han_ families and the two _Noto CJK_ ones, mainly because it is easier to keep a single file updated rather than a bunch of loose OTFs or OTCs. (The 142-font Ultra OTC is a mere 200K larger than the 78-font _Source Han_ Mega OTC.)

**Comment by ShikiSuen** [comment]
@kenlunde I see the OP's request is the availability of Source Han Sans as Windows default UI font for CJK languages. To me this requires extra necessary efforts from Microsoft. Also, due to some reasons (which are too Microsoft-confidential to say here) I guess Microsoft is less likely to do this.

**Comment by be5invis** [comment]
@kenlunde 
You can try to contact Basit Ali or Si Daniels.
But they wants VFs only now :p.

**Comment by kenlunde** [comment]
@be5invis I hope that our friends at Microsoft are prepared to support OpenType/CFF2 Collections (aka Variable Font Collections), because that is the only deployment format that makes sense for the _Source Han_ and _Noto CJK_ Variable Fonts. Any other deployment format defeats the size advantage of CFF2 by a factor of about five.

To this end, we're currently preparing a series of OpenType/CFF2 Collections that are intended to serve purely as test fonts for modern environments. Our first one, which was born last Tuesday, broke Adobe's apps, though HarfBuzz seems to handle it correctly. Of course, we have opened bugs against our apps, which are likely to result in a bug against a shared library.

**Comment by be5invis** [comment]
@kenlunde 
CFF2 support in Windows and Office is pretty complete, though there may be bugs. If you found any issue you can mail me (you should know my mail) and I will forward them to my colleagues.
