### ISSUE TITLE
The Same character is different in photoshop and libreoffice

### ISSUE THREAD

**Issue by Leroy-X** [adobe-fonts/source-han-sans#199]
![image](https://user-images.githubusercontent.com/13515498/45274869-e52c4c80-b4eb-11e8-90c5-18d4ef086d31.png)
photoshp

![image](https://user-images.githubusercontent.com/13515498/45274881-f2e1d200-b4eb-11e8-923a-a801dc2fd12a.png)
libreoffice

![image](https://user-images.githubusercontent.com/13515498/45274901-1b69cc00-b4ec-11e8-9984-c766131d0661.png)
illustrator

I am not understand how it work, so maybe it's not a problem,  by the way, copy this font from ps to libreoffice is become right, and paste to ai still problme. hope can help you.

**Comment by kenlunde** [comment]
Based on the font that is selected, U+6CBF 沿 is being rendered correctly in Libre Office and Illustrator. It is a Simplified Chinese font, in terms of the default glyphs. What is shown in Photoshop is the corresponding Traditional Chinese glyph, not the Simplified Chinese one. Please list the version numbers of Photoshop and Illustrator. It's possible that OS- or document-level language setting may be an influence, due to to the presence of the 'locl' GSUB feature that is sensitive to language settings.

**Comment by Leroy-X** [comment]
photoshop version: 19.1.2, 
illustrator : 22.1
system: win10 64bit 1803

I seem to have found the reason, the default font is multiple, when I selected USA, it's become right. sorry my poor english.

![image](https://user-images.githubusercontent.com/13515498/45284319-cc835d00-b512-11e8-9965-04916cf490cd.png)
![image](https://user-images.githubusercontent.com/13515498/45284334-d907b580-b512-11e8-9445-9a74b7832e53.png)
