### ISSUE TITLE
Useless space above the characters in CJK fonts

### ISSUE THREAD

**Issue by geniejhang** [adobe-fonts/source-han-sans#2]
I don't know why it is added but there's space above the characters so that it makes the character height taller than the actual character's height.

**Comment by ShikiSuen** [comment]
This reply only works for official SHS releases since v1.003:

The metrics (esp. Ascender and Descender in HHEA table) which Apple SD Gothic NEO used is mainly chosen for GUI font purposes. But that's a Korean-specific font family and, if they currently have no issues, no glyphs needs higher Ascender and Descender in HHEA table.

SHS releases since 1.002 uses LineGap=0 to improve its compatibility among most situations.
(e.g.: OS X's poor handling regarding LineGap-in-HHEA really irritates.)

But, only LineGap=0 is not enough. **Some glyphs, which SHS adopted, needs higher HHEA Ascender & Descender metrics**. Thus, they uses new Ascender and Descender in HHEA table since SHS 1.003 release (see their release notes for reason-in-detail). But this triggered the current #2 again. 

What I said "triggered" above **does not indicate** that it's an official bug, it **still** means as Ken Lunde claimed in "https://github.com/othercat/CJKFontScript/issues/5":
> It means that the **layout engine for the UI was poorly implemented**, or **references inappropriate fields in one or more tables** in the font.
![image](https://cloud.githubusercontent.com/assets/3164826/8265140/e513482e-1724-11e5-8125-df5e8b160dc2.png)
