### ISSUE TITLE
HK glyph issues for characters with “感”

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-sans#213]
This one is a bit complicated and need some more words.

Here are the BIG5 & HKSCS characters with 感 in their composition:

![c2](https://user-images.githubusercontent.com/959433/49432138-f2ef2680-f7e9-11e8-9d67-e0fc37ad6ad5.png)

-	Currently glyphs of *U+611F 感* and *U+6FB8 澸* are mapped to CN. But due to structural difference (⿹咸心vs ⿱咸心), HK cannot use CN glyphs.
-	For this two codepoints, it's more appropriate to use TW glyphs.
-	However, currently TW glyphs containing 感 are designed in a way such that the 一 component of 咸 sticks to the left stroke of the surrounding 戊 component. This is not the case for HK and other regions. And this explains why new glyphs are needed for U+61BE 憾, U+64BC 撼, U+8F57 轗.
-	Following this route, new glyphs would be needed for *U+611F 感* and  *U+6FB8 澸*.

That said, I also found that 

1.	TW glyph doesn't need to be designed this way. According to TW’s standard documents for [方體](https://language.moe.gov.tw/001/Upload/files/SITE_CONTENT/M0001/fangti/af13.htm?open) and [宋體](https://language.moe.gov.tw/001/Upload/files/SITE_CONTENT/M0001/SUNGTI/as13.htm?open) (No. 101402), the 一 is clearly separated from 戊. 

![c1](https://user-images.githubusercontent.com/959433/49432309-55e0bd80-f7ea-11e8-85e0-d31cd03d579a.png)

I suspect the current TW form was chosen due to an inconsistency in the design document (comparing the above image with the glyph of the MoE font, you can see that the placement of 一 is a bit different for 感), or it's based on an older version.

2.	Such design difference isn’t consistently applied to other codepoints - most are using the “non-sticking” version of 咸. For instance, U+54B8 咸 (share with JP), U+558A 喊 (share with CN) and even TW glyphs like U+8474 葴, U+9C75 鱵 and U+9E99 麙.

![c3](https://user-images.githubusercontent.com/959433/49432419-9b04ef80-f7ea-11e8-9bd4-c995ff924ebd.png)

So instead of adding new glyphs for HK, I’d like to propose to consistently use the "non-sticking" version by:

- modifying existing TW glyphs of *U+611F 感* and *U+6FB8 澸*, then share them with HK
- modifying the mapping of TW's *U+61BE 憾*, *U+64BC 撼* and *U+8F57 轗* to use the HK version
- optionally, consider changing the mapping of the following TW glyphs:

![c4](https://user-images.githubusercontent.com/959433/49432524-e15a4e80-f7ea-11e8-86d4-5bb2b0a51907.png)

| Codepoint | Remap Region
|  ------------- | --- |
| U+5D45 嵅 | JP
| U+6937 椷 | JP
| U+7158 煘 | HK
| U+7BB4 箴 | HK
| U+7DD8 緘 | CN

**Comment by hfhchan** [comment]
If it is possible, I would prefer to request that the current TW glyphs for 感 (even if their horizontal stroke adjusted) not be shared with HK.

For all commercial fonts distributed in Hong Kong, the structure has been consistently ⿱咸心.  Meanwhile, the HKSCS-2016 Kaiti and the original handwritten reference were written as ⿹咸心, as that form is more common .  For some unknown reason, HKSCS kept the Sungti as ⿵咸心, same as the Taiwanese cousins, rather than adjusting them to ⿹咸心 or ⿱咸心. 

Designing them as ⿵咸心 makes no sense at all since 心 is a horizontal component and squishing it into ⿵咸 looks hideous.  Even if Source Han Sans cannot redesign them as the most common form ⿱咸心, I would request that the form ⿹咸心 be used if possible.

Given such peculiar structure, even Microsoft Jhenghei, supposedly following MOE standards, was designed as ⿹咸心, similar to Kaiti reference instead of ⿵咸心 in Fangti reference.
![image](https://user-images.githubusercontent.com/8191296/49446190-8d616100-f80e-11e8-8366-d297ac200c5d.png)

**Comment by kenlunde** [comment]
@tamcy Whew! I managed to reflect the appropriate changes in Issues #202, #204, and #227. Please check when you have a chance.

**Comment by tamcy** [comment]
@kenlunde  Just checked the items, they all look good, thanks!
