### ISSUE TITLE
SuperOTC medium is not available in Photoshop

### ISSUE THREAD

**Issue by mshdyh** [adobe-fonts/source-han-sans#216]
### Prerequisites

Windows 10 Simplify Chinese
Photoshop
SuperOTC medium

### Description
 
Only SuperOTC medium can't display and report error. Other SuperOTC like regular, bold, etc.  are display normaly. On the other hand, if I install the single font form OTF or OTC folder, the medium font display correctly.

**Comment by kenlunde** [comment]
This is a known issue, and a bug has already been filed against Photoshop CC for Windows. Our testing also revealed that Illustrator CC for Windows is also affected. Until this is fixed in the apps, I suggest that you use the work-around that you described: install the weight-specific OTCs or individual OTFs instead of the Super OTC.

**Comment by pcb168** [comment]
Except medium the heavy weight is also unavailable with Adobe products, even for pdf files that are produced using Adobe acrobat from other programs like Microsoft word there is a problem that the pages are rendered totally blank...
