### ISSUE TITLE
OpenType feature half-width kana?

### ISSUE THREAD

**Issue by Stone-Zeng** [adobe-fonts/source-han-sans#217]
### Prerequisites

* [ ] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, JIS X 0208, JIS X 0212, and JIS X 0213 for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-sans/issues) and [closed](https://github.com/adobe-fonts/source-han-sans/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

How can I use the half-width kana (`U+FF60`--`U+FF9F`) from the normal form? The `halt` and `hwid` features both skip them.

Sometimes it's useful to use the half-width version, but it's not so easy to input them directly (via code point). So please consider to add an OpenType feature for switching to the half-width kana.

**Comment by kenlunde** [comment]
Registering a new OpenType feature would be a non-starter for such a conversion. Use [this converter](http://en.calc-site.com/letters/convert_full_half) instead.

**Comment by Stone-Zeng** [comment]
`ベ` etc don't have half-width version, so we must use `ﾍ`+` ﾞ`, which is not good:

![image](https://user-images.githubusercontent.com/18233088/50384825-7aeb9080-0705-11e9-979f-9d614fc78415.png)

Is it possible to add the half-width variants via `hwid`, like Kozuka Gothic Pr6N?

![image](https://user-images.githubusercontent.com/18233088/50384831-a0789a00-0705-11e9-9ec1-63720fa2b7fa.png)

**Comment by kenlunde** [comment]
Of course, it's _possible_, but there are far more higher-priority glyphs to consider, and when dealing with a glyph set that is already full, unencoded _dakuten_- or _handakuten_-annotated katakana is a very low priority. Furthermore, the use of half-width katakana should be discouraged, not encouraged.

Although a different matter, we already exorcized the half-width jamo in the same block by mapping them to the glyphs for the [Hangul Compatibility Jamo](https://www.unicode.org/charts/PDF/U3130.pdf) block, because we determined that half-width versions do not exist outside of Unicode. While we have no plans to do the same for half-width katakana, there is no practical reason to expand their glyphs.

Of course, this is an open source project, so feel free to do this for yourself.
