### ISSUE TITLE
font naming issue

### ISSUE THREAD

**Issue by eckdqja** [adobe-fonts/source-han-sans#220]
regular and bold name overlap
so 
at microsoft word, i can use six font(Nevertheless i install seven font)
![default](https://user-images.githubusercontent.com/46389810/50719530-9761d280-10e0-11e9-940b-292d8ee45080.jpg)

**Comment by kenlunde** [comment]
Per the statement on page 21 of the [ReadMe](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf), the Regular weight is style-linked to the Bold weight, which means for apps that support style-linking, such as MS Word, the "Bold" style button needs to be selected tp access the Bold weight. What you described is therefore expected behavior.

**Comment by eckdqja** [comment]
ok. thank

**Comment by kenlunde** [comment]
Happy New Year!
