### ISSUE TITLE
Is it possible to add character U+2C081 (𬂁, ⿰月君)?

### ISSUE THREAD

**Issue by yn0793** [adobe-fonts/source-han-sans#228]
This character is not in present standards but will be included in new GB-18030 which will be published in 2019. It's usually seen in words 𬂁肝 (⿰月君肝), which means gizzards. Gizzard is popular in south western China as a kind of food so this character can be seen in many restaurants' name and their signboard and menu. But all fonts included in phones and PCs don't support this character, so it's usually replaced by 郡, 郡肝. 
I think SHS has great influence because it's used in Android, Android is closer to people than iPhone and Windows, and many digital menu applications and systems are based on Android. Including this character in SHS can help solve many problems, and SHS can be more widely known and used.

Reference:
http://sc.ifeng.com/a/20171106/6122779_0.shtml

**Comment by eisoch** [comment]
We mentioned this character in IRGN2239 http://appsrv.cse.cuhk.edu.hk/~irg/irg/irg48/IRGN2239.pdf . In my opinion, it’s really used widely in mainland China. This request looks reasonable. 


在2019年03月01日 23:39，yn0793 写道：

This character is not in present standards but will be included in new GB-18030 which will be published in 2019. It's usually seen in words 𬂁肝 (⿰月君肝), which means gizzards. Gizzard is popular in south western China as a kind of food so this character can be seen in many restaurants' name and their signboard and menu. But all fonts included in phones and PCs don't support this character, so it's usually replaced by 郡, 郡肝.
I think SHS has great influence because it's used in Android, Android is closer to people than iPhone and Windows, and many digital menu applications and systems are based on Android. Including this character in SHS can help solve many problems, and SHS can be more widely known and used.

Reference:
http://sc.ifeng.com/a/20171106/6122779_0.shtml

**Comment by kenlunde** [comment]
Stating that this Extension E ideograph will be in the forthcoming new version of GB 18030 is not a very strong or compelling argument, mainly because GB 18030-2005 included Extension B in its entirety. For now, I have added to the list of candidates for Version 3.000, which is entirely unplanned, and therefore has no schedule.

**Comment by kenlunde** [comment]
I decided to squeeze this one in for the Version 2.001 update.
