### ISSUE TITLE
This font can't be embedded to Word and PDF

### ISSUE THREAD

**Issue by sy-github** [adobe-fonts/source-han-sans#230]
The font doesn't allow Word document to embed itself to the docx file, even if "embed fonts in the file" is ticked. Also when save a docx file to PDF, the text using this font are output as picture, not text, this matches the description when save as PDF in word dialog. It says "Bitmap text when fonts may not be embedded". 

No, this is nothing to do with "Office can't embed OpenType font", because latest Office 365 product explicitly support OpenType embedding, and other otf fonts can be embedded. According to some webpage, it says a font can be configured by font maker to allow embed or not. Are you sure you allowed embed feature for this font?

**Comment by kenlunde** [comment]
The [OS/2.fsType](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#fstype) value is set to 0 (zero), which is installable embedding. I suspect the presence of CFF outlines as apposed to TrueType ones may be the reason, but then again, I actively avoid using Microsoft apps for real-world purposes due to the poor (from my perspective) user experience. The other possibility is the size of the fonts or the number of glyphs, which tend to be greater than other comparable East Asian fonts.

About created a PDF, I suspect that you'll have better luck if you were print to PDF. (There is more than one way to create a PDF from an MS Word file, each with a varying degree of PDF quality.)

I'll keep this issue open for another day or two in the hope that someone who has more experience with font embedding in MS Word.

**Comment by khaledhosny** [comment]
AFAIK, Word does not support embedding CFF fonts in PDF, and I have seen this with many other CFF fonts.

**Comment by sy-github** [comment]
Ah, i see. So OpenType can have either TTF or CFF. Although word supports embedding OpenType it only supports TTF half. Is this right?

**Comment by khaledhosny** [comment]
Yes.

**Comment by kenlunde** [comment]
Many thanks, @khaledhosny, for chiming in.

**Comment by sy-github** [comment]
Is there method to convert from cff to TTF?

**Comment by miguelsousa** [comment]
Try the **otf2ttf** tool which is included in the **afdko** tool suite.
