### ISSUE TITLE
the ccmp browser compatibility problem

### ISSUE THREAD

**Issue by chenyin** [adobe-fonts/source-han-sans#232]
environment : Macbook Pro 2017 /  Chrome 73.0.3683.86
I want to show biang on my Chrome browser with no luck. After installed Source Han Sans V2.0, biang show on the Text app after using the font. Wonder to know what's the browser compatibility of "IDSes (Ideographic Description Sequences) and the 'ccmp' (Glyph Composition/Decomposition) GSUB feature"? btw I also tried 'font-feature-settings: "ccmp";' on chrome with no luck, as suggested by OpenType docs.

**Comment by kenlunde** [comment]
Have you tried [this](https://helpx.adobe.com/fonts/using/open-type-syntax.html#ccmp)?

**Comment by tamcy** [comment]
I also encountered this issue some weeks ago, and tend to beleive it's a browser issue. Unfortunately I don't have the time to further investigate on it before opening an issue on the Chromium and Firefox bug tracker. I'm on Windows 10 (64bit). 

Here's the codepen that illustrates the issue: https://codepen.io/tamcy/pen/YgKBqd

On Chrome it doesn't work at all (Chrome Canary 75.0.3757.0): 
![ccmp-chrome](https://user-images.githubusercontent.com/959433/55629248-55caeb80-57e5-11e9-9645-caf193310386.png)

The code works on Firefox (66.0.2), but only partially (only when the CCMP character is just after the opening part of a tag):
![ccmp-firefox](https://user-images.githubusercontent.com/959433/55629253-582d4580-57e5-11e9-8ed2-245b5a84b3bb.png)

Glyph Composition should be on by default, and in this case adding or removing the `font-feature-settings` CSS with or without vendor prefix doesn't do any difference.

**Comment by kenlunde** [comment]
As soon as Extension G is deemed stable, which should happen before the end of the year (because it is expected to be included in Unicode 13.0 whose repertoire will be frozen before the end of the year), I will issue a maintenance release that will map the four corresponding Plane 3 code points to these glyphs. Until that happens, it is best to consider the 'ccmp' treatment of these glyphs as a gimmick due to the limitations as demonstrated in this issue.
