### ISSUE TITLE
Language-specific or region-specific subset OTFs for Linux?

### ISSUE THREAD

**Issue by guoyunhe** [adobe-fonts/source-han-sans#234]
### Prerequisites

* [ ] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, JIS X 0208, JIS X 0212, and JIS X 0213 for Japan, and KS X 1001 and KS X 1002 for Korea.
* [ ] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-sans/issues) and [closed](https://github.com/adobe-fonts/source-han-sans/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [ ] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description
I am packaging Source Han Sans and Source Han Serif fonts for openSUSE Linux. I saw [this article](https://blogs.adobe.com/CCJKType/2014/09/shs-otf-or-otc.html):

> For those using Windows OS, only the OTFs can be used (unless the work-around described in the bullet above is used), and the choice boils down to the 65,535-glyph language-specific OTFs or the region-specific subset ones. The 65,535-glyph OTFs are recommended only if you use an application that supports the ‘locl’ GSUB feature and language-tagging. Otherwise, most users are better off installing the region-specific subset OTFs, which are not genuine Pan-CJK fonts. For both flavors of OTFs, there are sub-flavors that correspond to a language or region, which means that the default glyphs are appropriate for that language or region. If you are unable to language-tag your text, you must install and select the appropriate OTFs for your needs, in terms of language or region. If you need to support more than one language or region, you simply need to install OTFs for multiple languages or regions.

But they didn't say whether Linux support `locl` GSUB feature and language tagging.

Do you have any suggestion for choosing between language-specific or region-specific subset OTFs for Linux? Thanks!

**Comment by Explorer09** [comment]
The [readme](https://github.com/adobe-fonts/source-han-sans/blob/release/README.md) file in the release branch should be able to answer your question.

**Comment by kenlunde** [comment]
@guoyunhe **I recommend the 65,535-glyph language-specific OTFs.** Even if you use them in environments that do not support the 'locl' GSUB feature or language-tagging, there is still a default language, and they will behave like the region-specific subset OTFs, but with greater code point coverage.

If it were up to me, the region-specific subset OTFs wouldn't even be produced. They are not very interesting to me, primarily because they are not Pan-CJK fonts, which is the whole purpose of the _Source Han_ and _Noto CJK_ typefaces.

I am currently working on another _Source Han_ family, tentatively named _Source Han Mono_, which will be a Pan-CJK version of @hatchzo's [_Source Han Code JP_](https://github.com/adobe-fonts/source-han-code-jp/). I have no plans to develop region-specific subset OTFs.

**Comment by Explorer09** [comment]
@guoyunhe Objectively saying, the "region-specific subset OTF" is there mostly for compatibility with (legacy) applications that do not support language-tagging the texts.

The language specific OTFs would work equally well even if you don't use language tagging. The only catch for them is wasted disk space due to a lot of duplicated glyphs across multiple OTF files of different set languages.

The subset OTF are useful when you concern about disk space while using Source Han Serif/Sans for multiple languages, or when you simply don't want the pan-CJK coverage of the font (but why not if you have a lot of disk space to waste?)

By the way, what is your real use case, and why doesn't the readme answer your question?

**Comment by Firestar-Reimu** [comment]
@Explorer09 for example, I use Simplified Chinese as my default language on Linux and Windows.

And I also need support to Traditional Chinese, Japanese and Korean mainly on displaying these texts on my web browser, for example, ACG stuff.

I do not want to see: Chinese characters use Japanese glyphs (see [here](https://wiki.archlinux.org/title/Localization/Simplified_Chinese#Chinese_characters_displayed_as_variant_(Japanese)_glyphs)), or an article mainly in Chinese but some of the characters are displayed in Japanese glyphs

I have 2 questions:

- If I only install Source han sans SC, can these needs and do-not-wants be satisfied?
- If I install Source han sans CN, do I need to install TW/JP/KR to display Traditional Chinese, Japanese and Korean?

**Comment by Explorer09** [comment]
@Firestar-Reimu If your main use case is viewing web content, then it's recommended that you install Source Han Sans SC, the language specific version and not the region specific subset.

However, it _would_ include Japanese glyphs for certain CJK characters. It doesn't satisfy your do-not-want, but the inclusion of additional glyphs is a feature, not a bug. (Not including those glyphs would break the use case for viewing the web.)

Source Han Sans CN (the region specific subset) is for legacy apps that cannot support language tagging. In modern OSes, you don't use these for _displaying_ the Chinese text in UI. OSes have their language support packages - you should install those rather than just install the fonts.

**Comment by Firestar-Reimu** [comment]
So Source han sans CN does not contain TW/JP/KR glyphs or hiragana/katagana/hangul?
