### ISSUE TITLE
Words can't display correctly when import a EPS file into InDesign

### ISSUE THREAD

**Issue by bradleyni** [adobe-fonts/source-han-sans#235]
I have been used to use Source Han as preferred font when I create InDesign file, while recently I meet a big problem:
When I use Source Han font in Illustrator and create a .eps file, and then import it into InDesign, everything looks fine, but the exported PDF file from InDesign can't show the text of EPS correctly, all messy. Unless I outline the text of .eps file.

I have no idea why this happen and I had tested a lot, any possible setting of Illustrator and InDesign, no lucky.

**Comment by frankrolf** [comment]
Why the EPS detour? What keeps you from authoring the text directly in InDesign?

**Comment by frankrolf** [comment]
FYO: If there is Illustrator functionality you need that’s not available in InDesign, it is also possible to save PDF files from Illustrator, and import them into an InDesign file.

**Comment by kenlunde** [comment]
@bradleyni EPS feels so 20th century. PDF is more 21st century.

With that said, and as my esteemed colleague suggested, you'll have much better luck with importing PDFs, mainly because PDF does a **much** better job at embedding fonts, particularly CJK ones, than EPS.

If you insist on using EPS files for such a workflow, which would be a bad idea, you'll need to take this issue up with Illustrator, as the EPS-authoring app, or with InDesign, as the PDF-exporting app.

**Comment by kenlunde** [comment]
Please read [this](http://indesignsecrets.com/tiff-vs-psd-vs-eps-vs-pdf-vs.php).

**Comment by bradleyni** [comment]
Hi Frank

Thanks for your quick answer, and apologize if my English is not good, cause any confusion.

Yes either outline the EPS file or Create PDF and then import will resolve this issue. Or save AI file also works, it’s interesting.

The fact is that I don’t see same issue with any other font, so maybe something related to Noto/SourceHan I guess? I can use one of above option to solve it but it will cause extra effort, because I am translator company, my client provide the InDesign and EPS files, we translate them into Chinese or other language, without client’s approval I can’t change file type. So the only way for me now is outline EPS files, if cause extra time and make it hard for further update.

Thanks
Bradley

**Comment by kenlunde** [comment]
@bradleyni Keep in mind that the _Source Han_ / _Noto CJK_ fonts push many limits, and in this case the limit is likely the number of glyphs, and this has likely exposed an EPS limit, at least in your workflow. It has been nearly 20 years since I created or saved an EPS file.

I can generally do everything that I need to do in Design, but if not, I import either a PDF or PSD (Photoshop file format). When I am forced to use PowerPoint, anything that I cannot do directly in that app, which is most of [this presentation](https://adobe.ly/2udreIx), I import InDesign-exported PDFs.

**Comment by bradleyni** [comment]
Hi Dr. Ken

Thanks so much for all of your answers and suggestions, as well as the reference, they are really helpful. And I fully agree with you that create everything in InDesign.

But as I just replied in another mail to Mr. Frank, one of reasons I don’t intend to create PDF and then insert to InDesign, or save as AI is because we translate client’s files, without approval we can’t change file type. So current solution is outline the EPS file, this cause extra effort and make further update hard.

I raised this ticket is because I never meet same issue with any of other CCJK fonts in 10 years, so I guess maybe something the Noto font author team can check.

FYI I ever tried unembedded the font when I save EPS, when I try importing it into InDesign, it report fonts missing.
[cid:image001.png@01D4FECA.5CFFBDA0]

Thanks
Bradley

**Comment by kenlunde** [comment]
@bradleyni If your clients are supplying EPS files whose text content you are then translating into an East Asian language, the prudent thing to do is to inform your clients about this issue, and that there are superior file formats available.

The reason why you never encountered this issue before is because the number of glyphs in the _Source Han_ / _Noto CJK_ fonts is at the architectural limit (65,535), and also represent the most broadly distributed fonts with that many glyphs. Other East Asian fonts generally have less than half the number of glyphs as these fonts. We started to see issues when the number of glyphs exceeded 32K, and virtually all such issues have been fixed, at least in Adobe apps. Given that EPS is a dying format, I suspect that nothing can be addressed. And, it doesn't make sense to spend precious development cycles doing so.

You can certainly try to use the [region-specific subset OTFs](https://github.com/adobe-fonts/source-han-sans/tree/release/SubsetOTF) that have fewer (less than half) glyphs. It depends on whether the EPS issue is related to the number of glyphs or the values of the CIDs. If the former, using those fonts may solve the issue. If the latter, probably not.

**Comment by bradleyni** [comment]
Hi Dr. Ken

Thanks for all the answers, no lucky with region-specific subset OTFs<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadobe-fonts%2Fsource-han-sans%2Ftree%2Frelease%2FSubsetOTF&data=02%7C01%7Cbradley.ni%40welocalize.com%7Cb056195666f2474920ea08d6cc9fedb9%7Cd41d420e62654ec2aeb75869659e3fe2%7C0%7C0%7C636921384595173289&sdata=s8c9DxsH52kvPjuZQGryhHyNlqgSTHUnxDGNjlDO4zI%3D&reserved=0>, in this case, we will outline the EPS, or try other solutions, if we can’t persuade client to discard EPS format.

Thanks
Bradley

**Comment by monokano** [comment]
@bradleyni Try exporting EPS from InDesign and converting it to PDF in Acrobat Distiller. I think there is no problem with this method.

**Comment by bradleyni** [comment]
Hi Monokano

Thanks a lot, it do works! The only pity is that exporting page by page only, not a EPS for whole InDesign book.

Thanks
Bradley

**Comment by monokano** [comment]
@bradleyni Try creating a PostScript file.
[Create PostScript and EPS files](https://helpx.adobe.com/indesign/using/creating-postscript-eps-files.html)
