### ISSUE TITLE
SourceHanSansCN-Regular.otf has highest priority when matching monospace fonts in Linux (fontconfig)

### ISSUE THREAD

**Issue by guoyunhe** [adobe-fonts/source-han-sans#236]
### Prerequisites

* [ ] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, JIS X 0208, JIS X 0212, and JIS X 0213 for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-sans/issues) and [closed](https://github.com/adobe-fonts/source-han-sans/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

I have installed Source Han Sans CN fonts and found that it has highest priority in monospace fonts. Some web pages show code blocks with Source Han Sans CN Regular fonts, which is not aligned in English.

If I run `fc-match -a -s monospace`, I get:

```
SourceHanSansCN-Regular.otf: "思源黑体 CN" "Regular"
SourceCodePro-Regular.otf: "Source Code Pro" "Regular"
SourceCodePro-Regular.ttf: "Source Code Pro" "Regular"
SourceCodePro-Medium.otf: "Source Code Pro" "Medium"
SourceCodePro-Medium.ttf: "Source Code Pro" "Medium"
SourceCodePro-Light.otf: "Source Code Pro" "Light"
SourceCodePro-Light.ttf: "Source Code Pro" "Light"
SourceCodePro-ExtraLight.otf: "Source Code Pro" "ExtraLight"
SourceCodePro-ExtraLight.ttf: "Source Code Pro" "ExtraLight"
SourceCodePro-Semibold.otf: "Source Code Pro" "Semibold"
SourceCodePro-Semibold.ttf: "Source Code Pro" "Semibold"
SourceCodePro-Bold.otf: "Source Code Pro" "Bold"
SourceCodePro-Bold.ttf: "Source Code Pro" "Bold"
SourceCodePro-Black.otf: "Source Code Pro" "Black"
SourceCodePro-Black.ttf: "Source Code Pro" "Black"
SourceCodePro-It.otf: "Source Code Pro" "Italic"
SourceCodePro-It.ttf: "Source Code Pro" "Italic"
SourceCodePro-MediumIt.otf: "Source Code Pro" "Medium Italic"
SourceCodePro-MediumIt.ttf: "Source Code Pro" "Medium Italic"
SourceCodePro-LightIt.otf: "Source Code Pro" "Light Italic"
SourceCodePro-LightIt.ttf: "Source Code Pro" "Light Italic"
SourceCodePro-ExtraLightIt.otf: "Source Code Pro" "ExtraLight Italic"
SourceCodePro-ExtraLightIt.ttf: "Source Code Pro" "ExtraLight Italic"
SourceCodePro-SemiboldIt.otf: "Source Code Pro" "Semibold Italic"
SourceCodePro-SemiboldIt.ttf: "Source Code Pro" "Semibold Italic"
SourceCodePro-BoldIt.otf: "Source Code Pro" "Bold Italic"
...
```

However SourceHanSansCN-Regular.otf isn't a proper monospace fonts. Its Latin characters do not have same width. So it should have a lowest priority when matching monospace fonts.

I have installed all fonts weights of Source Han Sans CN fonts. Only the Regular font gets highest priority. All other font weights get low priority when matching monospace.

**Comment by kenlunde** [comment]
Please wait for _Source Han Mono_, which I am currently developing. It will be a Pan-CJK version of [_Source Han Code JP_](https://github.com/adobe-fonts/source-han-code-jp/). My current target is to release its 70 fonts, along with a 70-font Super OTC, by the end of this month.

**Comment by guoyunhe** [comment]
I still think this is bug. Any users who installed Source Han Sans will get wrong monospace fonts. It should have some property indicate it is not a monospace font.

**Comment by guoyunhe** [comment]
Confirmed with fontconfig developers. This is chosen by fontconfig, nothing to do with Source Han Sans fonts. If the system is Chinese language, fontconfig always pick a CJK fonts as monospace fonts.

**Comment by polarathene** [comment]
@guoyunhe yes, that's correct. [Arch Wiki advises](https://wiki.archlinux.org/index.php/Fonts#Fallback_font_order_with_X11) to set `LC_LANG` to `und`, otherwise chinese fonts will be preferred for english text.

You could also use your own fontconfig config to prefer your own font stack regardless. You might need to use a match rule that responds to locale if an alias->prefer rule alone for monospace is not sufficient.

The other cause as a monospace font fallback, is another issue with fontconfig. If you go into `/etc/fonts/conf.d/49-sansserif.conf`, you'll see this is where sans-serif is appended to any font that has not assigned itself a generic family at this point. So if you've selected a specific font in a terminal or editor for monospace usage, if there is no config file prior to that to handle the font(such as `66-noto-mono.conf` on Arch Linux which happens too late), sans-serif fonts will be assigned as fallbacks. 

I don't think you want both `-a` and `-s` options used with an `fc-match` query, one is unsorted/unfiltered list, the other is the opposite, `--sort` probably cancels out `--all`. To see the font list that is generated before filtering successive fonts and seeking additional fallbacks that don't meet the pattern/query, try:

`FC_DEBUG=4 fc-match monospace | grep -A2 "done"`

If you lack a config for handling the CJK fonts, it probably won't be listed in there, and the selection fails to meet the expected lang, which is found afterwards. 

Regarding true monospace font matching, `monospace` alone isn't enough, this is just a generic family name used in configs for matching. Terminal apps that provide a filtered list of monospace fonts are filtered based on a `spacing=100` property->value. You can query with:

`FC_DEBUG=4 fc-match monospace:spacing=100 | grep -A2 "done"`(optionally omit the `monospace` part.

or

`fc-list :spacing=100 family` (list of monospace fonts that a spacing value of 100 represents)

The spacing value is defined by fontconfig internally, and not something a font alone can add/force. All glyphs have to be equal width afaik for that to be possible.

---

Hope that helps you and anyone else that comes across the issue.
