### ISSUE TITLE
Fix for U+25C4A missing in Heavy weight

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-sans#283]
Version 2.002 includes a fix for U+25C4A (𥱊) where the top dot was missing in the 席 component. However, the updated glyph is missing in the heaviest weight:

![U+25C4A](https://user-images.githubusercontent.com/959433/103534295-916a7c00-4ec9-11eb-90c2-4ee6a5dffed2.png)

This is not a local installation issue. I tried downloading the [cidfont.ps.OTC.HC](https://github.com/adobe-fonts/source-han-sans/blob/master/Heavy/OTC/cidfont.ps.OTC.HC) file from Github, extract the reporting glyph (CID 60792) with `tx`, and inspect the exported glyph with FontForge:

![cid60792_ff](https://user-images.githubusercontent.com/959433/103534573-19508600-4eca-11eb-87cb-989f828c7e05.png)

It shows that the updated glyph is indeed missing in the Heavy weight.

**Comment by RuixiZhang42** [comment]
Is it possible that the “dot stroke” of the `广` component is *inside* (or *completely obscured*) by the “throw stroke” of the `⺮` radical? Since Adobe won’t release the source files for the master heavy-weight design *before glyph outlines are merged*, we can’t really “see” if the dot stroke is hidden in the other stroke…

**Comment by punchcutter** [comment]
This was a mistake and has been fixed for the next release.

**Comment by punchcutter** [comment]
Fixed in 2.003
<img width="124" alt="283" src="https://user-images.githubusercontent.com/11257204/113973186-d90cf500-9876-11eb-9f8a-91ad425df5fa.png">
