### ISSUE TITLE
The character "热" looks bad in 15px 96dpi with fontconfig 2.10

### ISSUE THREAD

**Issue by hexchain** [adobe-fonts/source-han-sans#285]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, JIS X 0208, JIS X 0212, and JIS X 0213 for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-sans/issues) and [closed](https://github.com/adobe-fonts/source-han-sans/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

I've recently noticed that the character "热" sometimes looks very bad in my browser. It seems that this character at this specific size (15px or 11pt/96dpi) is rendered incorrectly with FreeType 2.10. The same issue also happens with Noto Sans CJK.

```
ftview -m "热" -e unic 15 /usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-Regular.otf
```
![image](https://user-images.githubusercontent.com/529520/105041703-9c91e000-5a63-11eb-8548-c6c5bec07690.png)

Other sizes do not seem to have this problem:
![image](https://user-images.githubusercontent.com/529520/105041776-b4696400-5a63-11eb-9ee6-1f5526a5523b.png)
![image](https://user-images.githubusercontent.com/529520/105041822-c519da00-5a63-11eb-9527-d343065a3a2f.png)

I'm not sure if this is a font problem or an engine issue.

**Comment by lemzwerg** [comment]
Some  comments.

With FreeType, 

* character U+70ED gets correctly displayed with `SourceHanSansCN-Regular.otf` version 1.001, both hinted and unhinted, while
* character U+70ED doesn't get correctly displayed with `SourceHanSansCN-Regular.otf` version 2.002 if hinted (but everything is OK if hinting is disabled).

Disassembling the two font versions, I see that the hinting for this glyph is different.  It's hard to say without a slow and tedious debugging session whether there is a bug in the hints or not, or whether FreeType's Adobe hinting engine has a bug.  However, it looks quite suspicious that version 1.001 contains
```
219 69 77 73 123 70 -66 71 129 68 77 58 cntrmask (maskbytes: 0x69 0x00)
```
while version 2.002 has
```
219 69 77 73 123 70 -66 71 129 68 77 58 hintmask (maskbytes: 0x66 0xC0)
```
The use of `hintmask` instead of `cntrmask` in the 2.002 font looks like a typo.

Version 1.001, as displayed by `ftgrid`:

![1 001](https://user-images.githubusercontent.com/1630245/106663650-4ca73300-65a4-11eb-9619-0a2c9ae6160c.png)

Version 2.002:

![2 002](https://user-images.githubusercontent.com/1630245/106663672-5892f500-65a4-11eb-81d5-43388e224fcb.png)

**Comment by punchcutter** [comment]
Something seems to have been off with the hints in 2.002. 2.003 looks fine to me now.
 
<img width="632" alt="shs285" src="https://user-images.githubusercontent.com/11257204/114162965-9c1f2c00-9964-11eb-8fe2-5a25b0aaecdb.png">
