### ISSUE TITLE
Two extra-light weight and medium weight missing in variable font

### ISSUE THREAD

**Issue by WordlessEcho** [adobe-fonts/source-han-sans#291]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, JIS X 0208, JIS X 0212, and JIS X 0213 for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-sans/issues) and [closed](https://github.com/adobe-fonts/source-han-sans/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

[Please provide here a thorough description of the issue, being sure to specify at least a Unicode code point if it affects a character or a particular glyph for a character. Including the character itself after the Unicode code point also helps, for visual reasons. Images with annotations that pinpoint the issue also help. If you are referencing standards, please keep in mind that they may have known or unknown errors. It is not necessary to provide CIDs.]

First 250 weight. Second 300 weight.
![image](https://user-images.githubusercontent.com/12007025/114065287-12704f80-98cd-11eb-9bf4-7ccd5dabc184.png)

**Comment by punchcutter** [comment]
Same as https://github.com/googlefonts/noto-cjk/issues/190

Sorry about that. This is fixed for the next release. With the fix it looks like this:
<img width="468" alt="windows_fixed_STAT" src="https://user-images.githubusercontent.com/11257204/114121461-5db84b80-9929-11eb-8fd6-047bd735046d.png">
This only affects the Windows display name so the order you see is still correct, just the names are wrong because of the STAT table ranges.

**Comment by jimmymasaru** [comment]
In macOS, ExtraLight is shown as Regular in both Font Book and Pages. I'm not sure if that's related to this issue.
<img width="253" alt="screenshot" src="https://user-images.githubusercontent.com/12769660/114299653-98c8a380-9b10-11eb-90c0-081c7e7c554b.png">

**Comment by punchcutter** [comment]
No, that's a different problem with macOS only, but is also now fixed.

**Comment by punchcutter** [comment]
Fixed in 2.004

On Windows 20H2 19042.631
<img width="636" alt="shs-291" src="https://user-images.githubusercontent.com/11257204/116525156-32ff5880-a913-11eb-8f38-58ecd929b2f4.png">

On macOS 11.3
<img width="290" alt="shs291-mac" src="https://user-images.githubusercontent.com/11257204/116526487-9e95f580-a914-11eb-8539-43b40e3c0bf0.png">

macOS forces Regular to be on top even though ExtraLight is the default instance.
