### ISSUE TITLE
file size is larger than 30M，in browser will not take effect

### ISSUE THREAD

**Issue by forever-z-133** [adobe-fonts/source-han-sans#306]
The file size is larger than 30M，in browser will not take effect.  
字体包体积大于了 30M，造成浏览器中引入会警告，并不显示字体效果。

Ex:
错误表现如图：
![错误表现如图](https://user-images.githubusercontent.com/22021589/128795322-2c894502-4065-452c-a311-edce3a3bc767.png)

can you compress it？
大佬能不能给字体包压缩一下？最好能缩到 30M 以下，当然越小越好。

**Comment by tamcy** [comment]
1. The screenshot shows `SourceHanSans-Normal.ttf`. The official Source Han Sans release only provides OTFs for the 7 static weights, so what you are using doesn't belong to this repository. Such confusion is probably caused by some third parties converting and distributing another format of the font using the same "Source Han Sans" name.

2. The OTFs in this repository are all below 20MB.

3. Consider using a subsetted webfont, like [those provided by Google Fonts](https://fonts.google.com/?query=noto+sans). Or the [variable webfont](https://github.com/adobe-fonts/source-han-sans/tree/release/Variable/WOFF2) in this repository.

**Comment by forever-z-133** [comment]
Thanks

**Comment by josh-hadley** [comment]
The 30MB limit is coming from [OTS](https://github.com/khaledhosny/ots). The limit was raised significantly in [OTS v8.1.2](https://github.com/khaledhosny/ots/releases/tag/v8.1.2) from [PR 229](https://github.com/khaledhosny/ots/pull/229) in anticipation of Source Han Sans and many other large fonts growing well beyond 30MB when packaged as webfonts. It will probably take some time for browsers to adopt the newer OTS but eventually the size limit will be higher (300MB for total file size; 150MB for any individual table within a font).
