### ISSUE TITLE
不必要的地方差異

### ISSUE THREAD

**Issue by Guest-615695028** [adobe-fonts/source-han-sans#325]
1. 「妙」字中的「女」部件──不穿頭和保持橫筆的設計維持字形平衡和穩定。
2. 「零、孁」中的「雨」部件──採用「陸日韓」式，避免跳躍感。
3. 「與」字中上方和「數」字左下方──不強求所有筆畫依足手寫書體的細節，可以減少字體在小字號或粗體時的視覺干擾。
4. 「無」字和「⺮」部件，全部選用「陸日韓」版本的上下相連版本；「港台」版的不相連形態易引發視覺辨認混亂。
5. 「金、食」等字頂部的「人」部件，兩筆起筆在日韓版黏連，陸港台版則否（降低美觀），有辱華之嫌。但事實上黏連寫法在兩岸四地不違規，參見思源黑體的父字體蘋方。
6. 以下「昭源黑體」爲宜取形，「思源黑體」爲忌取形。
![familiar-1](https://user-images.githubusercontent.com/72639009/151129582-2959cd73-8752-450f-80c1-8e43a56b897a.svg)
![familiar-2](https://user-images.githubusercontent.com/72639009/151129586-b318921f-2a4a-4c62-bbb8-8c2e64351e6b.svg)
![print-1](https://user-images.githubusercontent.com/72639009/151129589-3ceba40a-a8a1-47ea-9ccb-649f1b1af1d3.svg)
![print-2](https://user-images.githubusercontent.com/72639009/151129590-d3c7e0e2-aa6d-4560-8ada-ecfd65957061.svg)
![style-1](https://user-images.githubusercontent.com/72639009/151129591-815d70f7-e8e5-4aaf-be39-c1cca09a216e.svg)
![style-2](https://user-images.githubusercontent.com/72639009/151129592-824f2aef-07c3-4f86-8d72-cc9983187049.svg)
![misc-1](https://user-images.githubusercontent.com/72639009/151129596-11539997-34db-4bc1-bfcb-f1c2570f457b.svg)
![misc-2](https://user-images.githubusercontent.com/72639009/151129597-d30998cc-6dec-4e2d-88d5-9d859b69f06b.svg)
消除這些差異（包括但不限於上文提及）有助於思源黑體集利用省下來的空間擴大字符容量。（例：非漢字區域照搬[Source Sans Pro](https://github.com/adobe-fonts/source-sans-pro)）
![pro-1](https://user-images.githubusercontent.com/72639009/151129602-6f49aa5c-cd6d-4139-b839-b78a0cfc2eed.svg)
![pro-2](https://user-images.githubusercontent.com/72639009/151129605-2e6ec877-51be-4ebd-8855-6e462fbdc840.svg)
。

**Comment by Marcus98T** [comment]
While I think that this issue on how much Source Han Sans and Serif should follow the Taiwan MOE style (and to a lesser extent, HKSCS style) is very debatable, I think it should be discussed with the design teams responsible for setting the glyph shapes [as I just said before](https://github.com/adobe-fonts/source-han-sans/issues/313#issuecomment-1022007263). We can't always get what we want... and some people prefer the Taiwan MOE style even if I personally feel that they're ugly, because they want a font that is consistent with people's handwriting.

**Comment by tamcy** [comment]
I am the author of [Chiron Sans HK](https://chiron-fonts.github.io/sans/), a open source font that is derived from the Hong Kong variant of Source Han Sans. As you have explicitly mentioned my font twice in this and your previous issue (#305), and because of the nature of your issues, I feel obligated to clarify  something here.

First, I have to make very clear that your original comment is using the texts and images from my Chiron Sans HK official website without my prior permission nor any attribution. Even worse, you modified texts from my website to suit your own propaganda, adding statements like "有辱華之嫌" (suspected to insult China/the Chinese), "忌取形" (forms [in Source Han Sans] that should be avoided) with images of my font (again, taken from my website) as examples, which may cause confusion that such statements reflect the stands of Chiron Sans HK or me. So let's be clear: **I am the sole author of Chiron Sans HK, and what this user @Guest-615695028 spoke here has nothing to do with me or Chiron Sans HK.**

One of the goal of Source Han Sans is an open source typeface that try its best to comply with the regional standard. It is understandable that not all people would agree with this approach, and personally, I also do not agree with every design decision chosen by the authority or the design team of the Source Han Sans typeface. That said, given the nature of Source Han Sans (which is also Noto Sans CJK, a system font deployed to Google's Android platforms), I fully understand the need for a standard-compliant font family (whether this is a mandatory standard doesn't matter) to avoid unneccessary disputes. And given the technical contraints and the vision of Source Han Sans (as a Pan-CJK typeface family), I also fully understand the need for sacrificing certain regional differences to achieve a larger amount of glyph sharing.

And for Chiron Sans HK, I started developed it for my own needs. I see it as my own vision of a sans-serif typeface, so I selected the glyph forms that I like more, and I modified the glyphs to suit my own need. I chose to make it available to everyone so as to provide another choice of freely accessible Chinese sans-serif typeface, one which style is usually found only in commercially developed products. My font isn't mean to replace the original Source Han Sans HK version, nor act as any proof or whatsoever that the original version hasn't done well enough. In fact, Chiron Sans HK could not be realized without the "base" provided by Google and Adobe and the open license chosen by them. So I am always thankful to what they have contributed to the community. I didn't even mention how numerous Linux GUI users have been benefitted by the quality of the font and Adobe's OpenType shaping engine.

While at it, let me also give a comment on your suggestion related to my font in #305, in particular the one to "廢香港版、HW諸版，香港已用昭源宋體代之" (nuke the HK, HW variants etc., as HK version has been replaced by Chiron Sans HK). I didn't comment on this because I didn't have the time and what you said was either not possible or just beating a dead horse, but here's my response anyway - I FULLY DISAGREE with what you said. The claim that Source Han Sans HK is "replaced" by my font is simply unfounded. And as I've just said, I positioned my font to be an alternative, not a replacement of Source Han Sans. Also, when I started working on Chiron Sans HK, I had decided to make it a downstream of the original project. I anticipated that this would allow me to adapt changes (especially fixes) of the upstream as quick as possible. This is a decision that I've never regreted: it wouldn't be possible for me to come up with a variable font vesion update in less than 2 weeks from the original release. So, nuking the HK variant of Source Han Sans is no difference to killing my project.

**Comment by Guest-615695028** [comment]
I support your view. Would you please add a Chiron Sans CN?

**Comment by Guest-615695028** [comment]
左山旁、左缶旁露腳不符合美觀需要，應調整。 · Issue #4 · chiron-fonts/chiron-sans-hk-pro (github.com)
要點：齒（繁簡）、缶、出、山、凵等含有底盤形塊的部件，應避免跛足，以保持結構穩定，其中現代明、黑體考慮使折筆露芒。若跛足的一邊還有部件，先天平衡了跛足的問題，則不在此限（屾右山不適用）；大陸、臺灣新字形令其單腳站立，搖搖欲倒，則失其美矣。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月26日(星期三) 晚上6:25
收件人: ***@***.***&gt;; 
抄送: "Jack ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [adobe-fonts/source-han-sans] 不必要的地方差異 (Issue #325)





 
I am the author of Chiron Sans HK, a open source font that is derived from the Hong Kong variant of Source Han Sans. As you have explicitly mentioned my font twice in this and your previous issue (#305), and because of the nature of your issues, I feel obligated to clarify  something here.
 
First, I have to make very clear that your original comment is using the texts and images from my Chiron Sans HK official website without my prior permission nor any attribution. Even worse, you modified texts from my website to suit your own propaganda, adding statements like "有辱華之嫌" (suspected to insult China/the Chinese), "忌取形" (forms [in Source Han Sans] that should be avoided) with images of my font (again, taken from my website) as examples, which may cause confusion that such statements reflect the stands of Chiron Sans HK or me. So let's be clear: I am the sole author of Chiron Sans HK, and what this user @Guest-615695028 spoke here has nothing to do with me or Chiron Sans HK.
 
One of the goal of Source Han Sans is an open source typeface that try its best to comply with the regional standard. It is understandable that not all people would agree with this approach, and personally, I also do not agree with every design decision chosen by the authority or the design team of the Source Han Sans typeface. That said, given the nature of Source Han Sans (which is also Noto Sans CJK, a system font deployed to Google's Android platforms), I fully understand the need for a standard-compliant font family (whether this is a mandatory standard doesn't matter) to avoid unneccessary disputes. And given the technical contraints and the vision of Source Han Sans (as a Pan-CJK typeface family), I also fully understand the need for sacrificing certain regional differences to achieve a larger amount of glyph sharing.
 
And for Chiron Sans HK, I started developed it for my own needs. I see it as my own vision of a sans-serif typeface, so I selected the glyph forms that I like more, and I modified the glyphs to suit my own need. I chose to make it available to everyone so as to provide another choice of freely accessible Chinese sans-serif typeface, one which style is usually found only in commercially developed products. My font isn't mean to replace the original Source Han Sans HK version, nor act as any proof or whatsoever that the original version hasn't done well enough. In fact, Chiron Sans HK could not be realized without the "base" provided by Google and Adobe and the open license chosen by them. So I am always thankful to what they have contributed to the community. I didn't even mention how numerous Linux GUI users have been benefitted by the quality of the font and Adobe's OpenType shaping engine.
 
While at it, let me also give a comment on your suggestion related to my font in #305, in particular the one to "廢香港版、HW諸版，香港已用昭源宋體代之" (nuke the HK, HW variants etc., as HK version has been replaced by Chiron Sans HK). I didn't comment on this because I didn't have the time and what you said was either not possible or just beating a dead horse, but here's my response anyway - I FULLY DISAGREE with what you said. The claim that Source Han Sans HK is "replaced" by my font is simply unfounded. And as I've just said, I positioned my font to be an alternative, not a replacement of Source Han Sans. Also, when I started working on Chiron Sans HK, I had decided to make it a downstream of the original project. I anticipated that this would allow me to adapt changes (especially fixes) of the upstream as quick as possible. This is a decision that I've never regreted: it wouldn't be possible for me to come up with a variable font vesion update in less than 2 weeks from the original release. So, nuking the HK variant of Source Han Sans is no difference to killing my project.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
