### ISSUE TITLE
Glyphs of U+5173「关」and U+590D「复」

### ISSUE THREAD

**Issue by Sleeplest** [adobe-fonts/source-han-sans#35]
These two glyphs have been displayed in an extremely narrow way.
![nthkliy uu8g sp_sqtb4](https://cloud.githubusercontent.com/assets/5804615/3641840/6af814d8-10b9-11e4-9b42-8f18e1499c92.jpg)

**Comment by leic4u** [comment]
Should I delete the Japanese font instances to avoid those narrow glyphs?

**Comment by szmcdull** [comment]
Since these two characters don't exist in Japanse, why they(the Japanse) put two narrowed glyphs in the corresponding code. Shouldn't they use separate codes? It seems to be a unicode bug for me, just like the left and right quotes. They should use different codes for full width and half width quotes

**Comment by ShikiSuen** [comment]
@szmcdull My deduction: These two characters are used as demonstratig the glyph components of kanji stroke combinations.
