### ISSUE TITLE
Shouldn't biáng (𰻞, U+30EDE) have a two-dot 辶 radical for JP?

### ISSUE THREAD

**Issue by Marcus98T** [adobe-fonts/source-han-sans#451]
Biáng (𰻞, U+30EDE) is technically a hyōgaiji kanji, therefore the 辶 radical should be two dots, not one.

I understand the multi-locale version of biáng was created to demonstrate what the special character would look like under different locales, and probably for fun, but it seems like this JP glyph for biáng is an exception to the hyōgaiji rule that normally dictates kyūjitai forms (basically traditional orthography). By right, the JP glyph should have two dots for the 辶 radical, and only the KR glyph has this.

<img width="323" alt="Screenshot 2023-08-03 at 23 31 54" src="https://github.com/adobe-fonts/source-han-sans/assets/10541683/c5fbe68f-fa13-4e8e-81c1-e077e3835298">

Unless this character is given a special exception ([there is a Japanese product packaging that shows biáng with one dot](https://blog-imgs-150.fc2.com/k/u/i/kuimakuru/202204018_1.jpg)), should the JP glyph be removed and the KR glyph be used for JP and KR?

Also applies to Serif.

<img width="358" alt="Screenshot 2023-08-03 at 23 32 11" src="https://github.com/adobe-fonts/source-han-sans/assets/10541683/a2f61f81-4589-458d-9f95-b26399636398">

**Comment by punchcutter** [comment]
I see both versions here in Japan and either way this isn't really worth an issue.

**Comment by Marcus98T** [comment]
> I see both versions here in Japan and either way this isn't really worth an issue.

That's okay. Anyway it's only one glyph so it will not matter much when it comes to reducing unnecessary CIDs.

**Comment by tats-u** [comment]
This kanji is probably an exception that uses 辶 instead of 辶 despite of the fact that it is not a joyo kanji.

<img width="600" height="600" alt="Image" src="https://github.com/user-attachments/assets/f9416e12-5126-410e-9fe9-7d0869b0e0b2" />

https://www.family.co.jp/goods/frozen_foods/3532089.html

<img width="296" height="170" alt="Image" src="https://github.com/user-attachments/assets/0f0b7b3e-78db-4404-9462-192f9764397d" />

https://weekly.ascii.jp/elem/000/004/274/4274679/

<img width="800" height="450" alt="Image" src="https://github.com/user-attachments/assets/98bea323-a439-4f7f-833a-c2c3251147ee" />

https://www.islog.jp/entry/byanbyanmen/

I have not seen the 辶 variant. I cannot completely deny that these glyphs have been influenced by the those of Source Han Sans/Serif, though.

Google image search link: https://www.google.com/search?sca_esv=39a7be05cc9c0b04&sxsrf=AE3TifNbl8qTkvAR8rrImq0uD4amIbHkiA:1765979815243&udm=2&fbs=AIIjpHyUpTfRVK7rDoqlzWEDmpyV0ik-IFrYG35KMbRhURnOYjotTZXM-wzUQk0zctqhoqNoE9T9iOwvPVShgtSOfZv4FFEzhIkuwTTH5UeoISNj8T5PSS4sRftlqBYLOcvGU3aVxeqRJmox64By_Er_GVJHPM6Dj4yW0tP9wSjQ11d4TuBeDJjZ32M4CjCwQoOwvqf7hKClp_ExrosFsRwJwoHOEHWxGGD5T1gePDfwClJAGyiiSfQ&q=%F0%B0%BB%9E%F0%B0%BB%9E%E9%BA%BA&sa=X&ved=2ahUKEwjdu8W848SRAxXRia8BHevtL0oQtKgLegQIMRAB&biw=1449&bih=868&dpr=2
