### ISSUE TITLE
請還原Traditional Chinese的眞正Tradition寫法

### ISSUE THREAD

**Issue by SyaoranHinata** [adobe-fonts/source-han-sans#6]
正體(繁體)中文所用的寫法，個人認為大有問題。從圖例顯示，寫法是向台灣敎育部靠攏。然而，使用正體中文的地區有許多，如香港、澳門和海外華僑等，其他地區並不以台灣寫法爲尚。此外，即使在台灣，過去舊日的書刊出版，乃至今天的報章，主要使用的也不是敎育部寫法。大家主要使用的，是過去傳統字書裏的正體寫法，有人稱作「舊字形」，日本朋友會叫「康熙字典體」——不是指某款遭濫用的字型，而是指參照同文書局原版的《康熙字典》每字字頭之寫法。這種寫法，一來有充份字理，二來在字型美學上也較美觀。至於台灣敎育部寫法，則以楷書寫法，來強行扭曲明體、黑體等印版字型，既缺乏字理，也不夠美觀，已有不少人詬病。在下由衷感謝　Adobe的貢獻，但極望　Adobe能把正體中文的字型，改回眞正正統的《康熙字典》寫法（即「舊字形」），而不是台灣以手寫楷書扭曲黑體的寫法。不勝銘感！

我不反對有台灣人想用台灣敎育部的寫法，但也應還其他Traditional Chinese使用者，使用眞正Tradition寫法的空間，分拆開「Taiwan」和「Traditional」兩體。而不是強迫其他正體使用者依從台灣那種以楷扭曲黑的寫法。

**Comment by ShikiSuen** [comment]
@kenlunde I don't think the issue #48 is addressing the concern written by the author of the first post in the current thread. His concern, from his perspective, is the essense of KangXi glyph standard. Both HKSCS and MOE are made against his concern of such. I am wondering whether such concern could be coped through 'trad' Opentype feature.

**Comment by hfhchan** [comment]
Ken, what are the concerns of adopting a traditional glyph forms, a lack of national standards or lack of a reference?

Also do you see any possibility of IRG reintroducing a "representative glyph" similar to the mode in Extension B by agreeing on a traditional orthography?

**Comment by kenlunde** [comment]
@ShikiSuen, @hfhchan & others: Adopting Kangxi-style glyphs is somewhat of a non-starter, at least for this project, along with its Google-branded clone, Noto Sans CJK.

For starters, the typeface style, sans serif, doesn't match that of the Kangxi dictionary, which means that some amount of extrapolation is necessary to accommodate the difference. However, in the context of this project, it is far more important to adhere to the standards on which it is based, meaning the appropriate GB, CNS, JIS, and KS standards, with HK to be supported in the Version 2.000 update.

Of course, this doesn't prevent anyone from forking this project and developing their own Kangxi-style version. My point is that it's not going to happen in the main branch. Besides, there are not enough CIDs to add glyphs in such a magnitude, and even supporting HK properly will require greater glyph sharing across regions, particularly between CN and JP.

**Comment by hfhchan** [comment]
Traditional forms have been very widespread in print, until recently when lead-type and phototypesetting processes are now replaced by digital fonts.  Few digital fonts using traditional orthography are available for purchase, and even less that are truly free.

Would Adobe consider developing any open-source traditional orthography font, with or outside the confines of Source Han Sans?  Given the shear amount of glyphs involved, and the number of weights involved in Source Han Sans, it would take considerable effort to develop and maintain -- resources that can only be put in by large corporations.

For Adobe, it means altering the two masters, but for forkers it means altering 7 glyphs per character.  Traditional orthography has been largely ignored by China, Taiwan and Hong Kong, dismissing them as "compromises that should be banished" or "illegitimate forms" downright. It would be a great loss to see them go just because they are not standardized nationally.

@SyaoranHinata and I would very much like to help but we possess little knowledge in modifying the ps files nor font generation.

**Comment by ShikiSuen** [comment]
@kenlunde 

1. I don't mean whether the thread-starter's concerns should be addressed or not; I just point out that making HK branch does not equal to address such concern.

2. Thanks for your explicative reply. This leads to my question: Supposed that KangXi style is standardized someday in the future, will it be taken consideration even if it is not a national standard?

$ EOF.

**Comment by zerng07** [comment]
@hfhchan After reading the replies by Ken above, I believe that what you propose is totally out of the scope of this project (Source Han Sans or Noto Sans CJK) although I also agree with the perspective that Kangxi dictionary style glyphs are valuable.
By the way, people-powered or crowdsourced projects might be a solution to build/fork such a variant. WenQuanYi and Hanazono have proved the possibility of co-work fonts. That might be something with more possibility to happen in the future. Never expect some big companies to jump in and do the requests which takes a lot of man-power, time and money by everyone who just leaving some comments.

**Comment by hfhchan** [comment]
@zerng07
> Never expect some big companies to jump in and do the requests which takes a lot of man-power, time and money by everyone who just leaving some comments.

I find this statement to be produced from a government official of a totalitarian state, not from supporters of open source.  Open source relies on individual contribution as well as support from large corporations.  I don't see why you're in favour of suppressing other's legitimate needs.

@kenlunde, @SyaoranHinata and I are developing a traditional-orthography Mincho style font on GlyphWiki.  I am interested if you think IRG would accept such a proposal for orthgraphy standardization (as additional reference or "representative" like in Ext. B) in the near future, and any actions that we may take to increase its chance of success.  If it were standardized by IRG, I guess no one needs to worry about lack of font support.

**Comment by kenlunde** [comment]
I agree that the KR forms tend to be closest to what is shown in the Kangxi dictionary. The coverage of KR forms is limited to those characters that correspond to KS X 1001 and KS X 1001, which is about one-quarter of the CJK Unified Ideograph coverage of Source Han Sans.

One of my side-projects is a continuation of my [Genuine Han Unification](https://blogs.adobe.com/CCJKType/2012/01/genuine-han-unification.html) presentation at IUC35 that could result in something that is relatively close to this expectation, specifically a font for which a single glyph is provided for every CJK Unified Ideograph, and is future-looking in that the most common form among the regions that use these characters is preferred. Unfortunately, there would be plenty of differences.

In the case of U+9AA8 骨, only China and Taiwan use forms that are different from the Kangxi form, and Japan, Korea, and Hong Korea effectively use the Kangxi form.

In terms of getting Kangxi forms reflected in the code charts, a new IRG source would be required, and a horizontal extension would also need to be submitted that provides source references for the new Kangxi-base IRG source. This is not impossible, but would require a lot of work.

In terms of the current project, Issue #119 should be referenced. For the Version 2.000 update, I am considering the possibility of adding the masters, meaning ExtraLight and Heavy, in a form that is compatible for interpolation purposes. This would make it easier for forked versions of the project to modify existing glyphs or add new ones. That is why that particular issue has been left open.

**Comment by c933103** [comment]
Because Kangxi form is the most region-neutral form as it is recognized by almost all region as some kind of original standard, would it be a good idea to make a Kangxi style variant and make it the default for any users who oes not specify what variant they want? For instance, when a random American user want to add some Han characters into a webpage/pdf/etc., it's very likely that the user would not know about those font/style/variant needed to display the character correctly and their system will not have the setting that specify should it use TW/CN/JP/KR form, because the user is in US. As such, even if the user is actually typing a Japanese essay, every kanji in his pdf will still be appeared as the China variant if the user is not computer literate enough about how fonts are displayed which can create quite a few problems.
While the problem seems niche at the beginning, given the extent of globalization it could affect every users, for instance https://www.reddit.com/r/LearnJapanese/comments/1ju178/android_phones_display_some_kanji_incorrectly/ every Android phone with version number below 4.1 would display kanji in China version of the glyph which demonstrated what effect would happen if China standard is treated as the default. When even Google need to spend 4 years before they make a version that can display Japanese glyph for Japanese  user, little hope can be given to other program developers. At least if a Kangxi standard is used, they will simply be old but not wrong when people forgot to cater about that.
And in the linked post you can also see that the glyph problen still affect some Android users nowadays, as there are millions of people learning Japanese around the world or speaking Japanese as secondary language, those millions of people are more likely to interested in Japanese glyph instead of China's glyph, but if they are still using their native language on their phone then such thing cannot be done and they would be forced to choose between using their phone in native language but see kanji in China's glyph or have a Japanese environment in their phone just to get the correct glyph display. I thibk kangxi variant for non CJKV environment can at least reduce the problem from displaying wrong variant to display traditional variant.

**Comment by kenlunde** [comment]
I understand and appreciate the potential value for such a region-agnostic font, but given the requirements of Source Han Sans (and the Google-branded clone, Noto Sans CJK), along with the fact that there is no space (the glyph set is literally full), it won't happen in the main branch. This seems like a worthy longer-term goal that is best implemented as a separate branch, which also ties in nicely to my [_Genuine Han Unification_](https://blogs.adobe.com/CCJKType/2012/01/genuine-han-unification.html) idea, or is at least related to it in that a single form would be used for each code point.

**Comment by KrasnayaPloshchad** [comment]
I think this should be develop as separate project as “Source Han Sans Classical”.

**Comment by KrasnayaPloshchad** [comment]
There is a resource available 
http://www.kangxizidian.com/

**Comment by kenlunde** [comment]
Thank you. I was already aware of this resource.

**Comment by ShikiSuen** [comment]
Till now, the most irritating thing hinder people from each side being satisfied is that they always treat what they supported are the best **substitution** of what they dismissed. After reviewing this issue, I think both of these glyph standards are worth being taken consideration. The reason why MOE is supported earlier is led from a general sense of respect to any of "governmental" "official" standards from authorities. However, this is not the reason to completely dismiss the standard of KangXi glyph styles. Regarding the availability of the KangXi branch of SHS, only time and Adobe official consideration could tell in the future.

**Comment by KrasnayaPloshchad** [comment]
To my eyes, the standard of KangXi glyph styles is not a govermental standard, it’s _de facto_ standard that has wide spread in East Asian printing industry, and before some governmantal standards appearing.

**Comment by KrasnayaPloshchad** [comment]
I have noticed [DynaComware Corp.](http://www.dynacw.com.tw/support/support_download_list.aspx?sid=6) have produced some series of font under the name of DFMing, DFHei and DFYuan, the design looks very similar to what I have seen on some older books and newspapers, also set an good example of this.

**Comment by ShikiSuen** [comment]
@KrasnayaPloshchad The Unicode version of DFHei and DFMing are MOE fonts.

**Comment by KrasnayaPloshchad** [comment]
@ShikiSuen Oh...I made a mistake, they are DF**P**Ming, DF**P**Hei and DF**P**Yuan.

**Comment by infinnie** [comment]
@KrasnayaPloshchad In most cases, the letter “P” occurring at the prefix position of a font name means that the typeface bearing the name is a *p*roportional font, and hence the name.

**Comment by ShikiSuen** [comment]
Disclaimer:

Since the start of this thread till now, @SyaoranHinata still felt pissed off regarding the fact that no one fiercely reject @RJHsiao 's idea. He even think my initial idea supported @RJHsiao. To comfort @SyaoranHinata and clarify my unchanged idea, here comes my additional explanation towards all my reply above:

1. I am still looking forward to see KangXi branch of SHS for the sake of supporting the glyph style with closest relation to the history of ideograph variation.

2. My idea above shall not be made with sacrificing the MOE branch of SHS.

3. This means I support both MOE branch and KangXi branch.

4. I said `"That's not @SyaoranHinata 's standard, there's currently NO standard for what @SyaoranHinata want."` because I realized that Adobe needs a standard manuscript (a book instructing every KangXi ideograph should look like) in order to build the KangXi branch of SHS efficiently.

5. KangXi branch is definitely not to personally satisfy @SyaoranHinata, but to satisfly more people not being participated in this thread.

6. `"Adobe and Google are not responsible for making a font based on an unstandardized glyph sets. That's what I supposed."` does not indicate that it is a good idea to let Adobe and Google completely give up the idea of making the KangXi branch of SHS. As what I addressed above: `"…for the sake of supporting the glyph style with closest relation to the history of ideograph variation."`, I really hope that Adobe could think thrice for the cultural meaningness of making a KangXi branch for SHS.

7. Maybe @RJHsiao 's responsibility of making an apology to @SyaoranHinata is still being doubted, but I don't think it is a good idea to sacrifice KangXi branch. My idea is to keep both KangXi and MOE due to their different cultural purposes. Hope that @RJHsiao thinks the same as mine.

$ EOF.

**Comment by ShikiSuen** [comment]
Just a quick notice to email subscribers that I modified my previous reply to address something supplemental.

**Comment by KrasnayaPloshchad** [comment]
On _Type is Beautiful_ I have also found this design even on several pictures from Chinese Bible, even if they looks a bit ugly.
http://www.typeisbeautiful.com/2016/12/11232/zh-hant/

**Comment by c933103** [comment]
- As the PanCJKV IVD collection proposed by Adobe will include a pseudo region of KangXi, would it be possible to include KangXi as a pseudo region in font release, if glyph restriction is no longer a limit?
- Is it possible to bypass the 65535 glyph restriction limit by spliting CJK fonts into multiple different fonts like code 2000/2001/2002 and then bundle them together into a single super otc?

**Comment by kenlunde** [comment]
@c933103: With regard to:

> As the PanCJKV IVD collection proposed by Adobe will include a pseudo region of KangXi, would it be possible to include KangXi as a pseudo region in font release, if glyph restriction is no longer a limit?

That's a loaded question, because there is still a 64K-glyph limit, and a non-zero amount of work is involved in producing a more complete set of so-called _ Kangxi_ glyphs.

> Is it possible to bypass the 65535 glyph restriction limit by splitting CJK fonts into multiple different fonts like code 2000/2001/2002 and then bundle them together into a single super otc?

Please understand that OTCs simply represent a packaging of separate fonts. While some OTCs may share 'sfnt' tables, sharing of tables is not necessary. The fonts included in an OTC are still considered to be separate fonts by applications and environments that can consume them, meaning that some form of font fallback or composite font is necessary for them to be used together.

**Comment by KrasnayaPloshchad** [comment]
I have discovered two fonts derived from Source Han series, and the design is very suitable to what you need.
https://github.com/ButTaiwan/genyog-font
https://github.com/ButTaiwan/genyo-font

**Comment by SyaoranHinata** [comment]
> I have discovered two fonts derived from Source Han series, and the design is very suitable to what you need.
> https://github.com/ButTaiwan/genyog-font
> https://github.com/ButTaiwan/genyo-font

However, they are useless unless they were supported by the official, as a normal user cannot change the system font without rooting the phone, but we will lose the warrant if we root it.  Besides, the cloud font of Google or Adobe only provides the official version, that means we are still forced to use MOE fonts, our right of choice is disappeared.

**Comment by aikahiiragi** [comment]
In the academic field of Chinese philology, every scholar knows that the Glyph list of Kangxi is a set of standard, it perfectly fits the definition of "standard". 

A software engineer, who knows nothing about philology, should apologize for claiming that Kangxi is not a standard, which is completely contrary to fact of academic.

**Comment by ShikiSuen** [comment]
@aikahiiragi Stop throwing your loaded language here.
If you want to make it into a standard, you are supposed to seek help from people work in W3C.
Besides, the engineer you want to blame is not working for Adobe and this project anymore since September 2019.

**Comment by hfhchan** [comment]
I believe @aikahiiragi was referring to @RJHsiao in response to his following remark:

>  I Have to say, 康熙字典"Kangxi Dictionary" and 大漢和”The Morohashi dictionary/The Dai Kan-Wa Jiten” are **YOUR standard**, **NOT the REAL standard**. In fact, no one said they are **standard BUT YOU**.

And not referring @kenlunde, who has expressed his understanding for historical significance for the Kangxi glyph forms in multiple venues.

**Comment by hfhchan** [comment]
> @aikahiiragi Stop throwing your loaded language here.

> I Have to say, 康熙字典"Kangxi Dictionary" and 大漢和”The Morohashi dictionary/The Dai Kan-Wa Jiten” are YOUR standard, NOT the REAL standard. In fact, no one said they are standard BUT YOU.

> So I said that they are @SyaoranHinata's standard but not the real standard. Don't you agree me?

> I think he just want someone can develop a font that following his wish and have opportunity to become standard, but why the developers in Adobe and Google have to work for his wish?

I believe @RJHsiao's initial accusations were very loaded and very disrespectful to other users of Traditional Chinese.  Taiwan is not the sole user of Traditional Chinese, and peddling that other preferred and well-established orthographies are someone's own standards seems to be using inflammatory language.

@ShikiSuen's addition comment here also used inflammatory language:

> @RJHsiao 嗆你說那是你的標準，
> 自然是因為他看你這樣用驚嘆號脾氣暴躁、導致他不屑理解你那標準是三小。
> 你這樣打雞血的態度不會幫你解決任何問題，真的。

translated as follows:

> @RJHsiao yelled at you saying it's your own standard,
> is naturally because he saw you using an exclamation mark, showing your temper, leading him not to understanding what the fuck* your standard is about
> this kind of "blood coming out of eyes" attitude will not help you solve any problem, I mean it.

* 三小 literally means "what sperm"

Since this thread is going nowhere, I hereby request Adobe to lock this thread and remove the abusive comments.

**Comment by hfhchan** [comment]
@ultrasparky

**Comment by RJHsiao** [comment]
看到這 issue 又被拉出來討論了，我還是簡單述說一下我的想法。
請原諒我只用中文打出來，因為我想大部分在這邊討論爭執的人都是懂中文、對中文字體設計有一定想法的人。
而且我的英文其實不好，這篇要打英文應該就會打到明天白天了吧...

首先，我要先說我先前所提到的標準，就是像 W3C、ISO、IEEE、JIS 等這些由有公信力的組織、政府機構「白紙黑字」明文制訂的標準，而康熙字典體就算在學術界上被認為是「有權威性的字書之字形寫法標準」，但在被真正訂為標準之前，頂多就是一個非常有權威的字形寫法。
況且字形寫法本來就會隨時代變化，字體的設計也會隨目的的不同而做調整，要讓某個寫法被視為最正確的寫法並訂為標準我是覺得不現實且沒意義。

Adobe 與 Google 為了他們的目的去合作設計出思源黑體並開源出來本來就是一件很好的事情，這點相信大家都認同。
但畢竟這兩家公司本就不是在做慈善事業，他設計這套字體本來也只是要完成他們的目標，
因次如果是有些 bug 要調整的提出來沒什麼問題，但押著要他們大幅修正去往一個根本就不是標準的「權威性的寫法」去靠攏我覺得大可不必。就算康熙字典體的寫法多麼具有權威性，也是有這個字體要達成的目的，且這個目的不一定能跟 Adobe 與 Google 他們的目的毫不相衝，且就算真的毫不相衝， Adobe 與 Google 也沒必要特地再花費精力去迎合部分人的「提倡」。若真的覺得這個提倡可以做，那大概也是另外出一套字體就好了，沒必要把原本辛勤的工作成果覆蓋過去。

就如我先前就說的，字體是開源的，有人有什麼自己的需求就 Fork 去改，不會有人阻撓，而現實上就有不少這樣的專案出來，那有些人還在爭什麼呢？如果是因為沒有能力的話，那應該要用合理的理由、理性的態度去說服人家幫你達成你的願望，而不是用否定他人工作成果的方式。

最後要聲明，我其實一點也不 care 思源黑體的寫法有沒有/要不要參照台灣教育部的標準，我想說的就是思源黑體已經被設計出來了，而且看起來是有達成設計師及公司所規劃的目標了。字寫出來就是要傳遞消息及達成寫字的人所期望的目標，設計字體也是，字體寫得「正確」與否是否是那麼重要的事情？一些字體為了美觀、辨識度及其設計的目的而對字的寫法、架構作調整，而不完全遵照台灣教育局的標準或是學術界的「標準」真的是很嚴重的問題？或是某些字以台灣教育局的標準來設計是必須大聲撻伐的事情？
由一個作為單純的字體使用者，沒有參與過字體的設計與開發的我來看，只會覺得有些人爭論的點真的有意義嗎？其實只是某種成見吧？

寫到這邊，覺得已經脫離「簡單述說」的範疇了，
就跟有人一開始只是訴求按地區拆分結果演變成拿一個權威性的寫法去覆蓋一個已經完成的工作成果還蠻像的。

最後的最後，再來吐槽一下：
1. 有人說普通用戶不 Root 手機就不能改字體，Google 不提供支援就等於失去選擇，那我看到一堆不會 Root 手機的使用者拿著沒 Root 卻以娃娃體作為顯示字體的手機又是怎麼一回事呢？
2. 這 Issue 開到現在已經6年了，有心要做一套基於康熙字典體的思源黑體的話不是早就完成了？我沒參加過字體開發，還請有實際經驗的先輩解惑一下

**Comment by c933103** [comment]
標準有兩款，de facto和de jure。事實標準和法定標準。不是只有政府或官方組織規定的法定標準才是標準。

至於手機字體的問題，三星等一部分手機廠商有官方字體商店，可供用戶購買Monotype等廠商發售的字體。娃娃體是其中一種可供選擇的字體。

至於你說私人開發基於康熙字典體的思源黑體，網絡上其實已經存在，但由於未獲廠商官方支援而缺乏互換性。

**Comment by hfhchan** [comment]
If you define standard as being promulgated by a particular government or international entity then Kangxi forms are indeed not promulgated by any modern government. But that is clearly a very narrow view, considering that Japan falls back to Kangxi form and Korean mostly uses Kangxi form, and Kangxi form is still very widespread in Taiwan, Hong Kong and Macau, especially in commercially printed articles.

> 就算康熙字典體的寫法多麼具有權威性，也是有這個字體要達成的目的，且這個目的不一定能跟 Adobe 與 Google 他們的目的毫不相衝，且就算真的毫不相衝， Adobe 與 Google 也沒必要特地再花費精力去迎合部分人的「提倡」。若真的覺得這個提倡可以做，那大概也是另外出一套字體就好了，沒必要把原本辛勤的工作成果覆蓋過去。

The existence of the wide variety of derivatives surfacing of existing Kangxi forms and supplementing forms for characters not supported by J/K standards already show there is considerable demand by users.

> 但畢竟這兩家公司本就不是在做慈善事業，他設計這套字體本來也只是要完成他們的目標

It's up to them to decide whether or not they want to support this user subset.  I find your attitude condescending for a native speaker to come over and call other native speakers' actual requirements as unnecessary.

> 有人說普通用戶不 Root 手機就不能改字體，Google 不提供支援就等於失去選擇，那我看到一堆不會 Root 手機的使用者拿著沒 Root 卻以娃娃體作為顯示字體的手機又是怎麼一回事呢？

Up until Android 9, most vendors shipped their own CJK fonts with their devices.  Since CJK fonts are so large, it is not very possible to ship with alternate sets, although the situation is alleviated somewhat with increasing memory. Source Han Sans already contains a large amount of Kangxi forms, activated by default in the Japan & Korean locales.

Other vendors ship with commercial fonts covering only the most common characters as themes.  The gist of this issue to to support displaying the conventionally designed glyphs for Traditional Chinese.

> 就如我先前就說的，字體是開源的，有人有什麼自己的需求就 Fork 去改，不會有人阻撓，而現實上就有不少這樣的專案出來，那有些人還在爭什麼呢？如果是因為沒有能力的話，那應該要用合理的理由、理性的態度去說服人家幫你達成你的願望，而不是用否定他人工作成果的方式。

> 這 Issue 開到現在已經6年了，有心要做一套基於康熙字典體的思源黑體的話不是早就完成了？我沒參加過字體開發，還請有實際經驗的先輩解惑一下

Apparently the issue author and many other proponents of a conservative orthography mentioned in this thread have been shipping various open-source fonts for years.  I recommend against subtle accusations of people being whiny.

**Comment by RJHsiao** [comment]
這樣阿，
因為我不是傳承字形的擁護者，
所以我其實不太懂已經有人弄出來了那還要原廠去「還原」的用意其實是塞進所有 Android 裝置裡面。
我覺得你們去 Android Develop 那邊請願開放可以讓用戶自行安裝/選擇字體，
對你們的訴求「讓使用者可以選擇使用傳承字形」來說這才是比較合理的解法。
雖然我同時也不是國字標準字體擁護者也不 care 這些事情，但你們現在要求「還原」的作法也是在剝奪他們的選擇權。
而且這顯然不是思源黑體本身的錯誤 - 雖然可能這邊的很多人不認同。

至於標準什麼的，前面有講了，在這個討論中我對標準的定義是很狹隘沒錯，不過重點也不在這邊，
畢竟對我來說這些並不是設計字體時絕對必須考慮的點，雖然可能也是有很多人不認同我。

另外對於系統字體那部分還有這邊提倡傳承字形的人大多都是有貢獻的這部分是我用功不足，在此說聲抱歉。
也請容許我抽離這個討論...雖然是我自己跳進來的，因為顯然討論下去不會有交集。

**Comment by danrhatigan** [comment]
The substantial enhancements to glyph repertoire of Source Han Sans as discussed in this thread are, unfortunately, beyond the scope of Adobe's current plans and capacity to investigate further. If we are able to revisit this in the future, we will reopen investigation into what would constitute an appropriate set of glyphs.
