### ISSUE TITLE
Unnecessary space appears in each glyph while using with Microsoft Word 2011 for mac.

### ISSUE THREAD

**Issue by ShikiSuen** [adobe-fonts/source-han-sans#62]
![image](https://cloud.githubusercontent.com/assets/3164826/4262421/c7068742-3ba1-11e4-95c7-ab55a6949ed3.png)

**Comment by kintopp** [comment]
This looks to be fixed in the Office 2015 Preview (http://products.office.com/en-US/mac/mac-preview) along with much better Asian language support in general.

Office 2011:
![screen shot 2015-03-05 at 7 38 12 pm](https://cloud.githubusercontent.com/assets/963588/6511792/4cb5dcb2-c36f-11e4-822b-2755104f7788.png)
Office 2015 Preview:
![screen shot 2015-03-05 at 7 37 45 pm](https://cloud.githubusercontent.com/assets/963588/6511800/59118b28-c36f-11e4-9c76-07d168ca6954.png)

**Comment by kenlunde** [comment]
Nice! Thank you for posting this encouraging news.

**Comment by kenlunde** [comment]
Given what has been discussed, this is clearly an issue with MS Word, and any fix needs to come from Microsoft (they are aware of this issue). I am closing the issue, and will re-open if deemed necessary.

**Comment by kenlunde** [comment]
I just installed Microsoft Office 2016 for Mac, and this issue seems to have been fixed.
