### ISSUE TITLE
Character ㌬(U+332C) is being mojibake

### ISSUE THREAD

**Issue by hurss** [adobe-fonts/source-han-sans#78]
There is a matter about character ㌬(U+332C).
㌬(U+332C; SQUARE PAATU), which means "parts"(パーツ) in Japanese, have still not shown correct from in character map. It is mojibake character but it not have fixed while Source Han Sans up to V1.001.

I don't know why this character is "excluded" in Source Han Sans series though It seems to be critical problem. Also, I hope this issue don't want neither overlapped previous issue nor closed.

![sourcehansans_parts1](https://cloud.githubusercontent.com/assets/8635567/4825798/328ebd6e-5f69-11e4-8ed7-b3e706c6b622.PNG)
[Figure 1] Only Source Han Sans not applied appropriate font style. (Also, default font style is MS Mincho.)
![sourcehansans_parts2](https://cloud.githubusercontent.com/assets/8635567/4825799/3297e632-5f69-11e4-94e3-ed7ad0047ea6.PNG)
![sourcehansans_parts3](https://cloud.githubusercontent.com/assets/8635567/4825887/40d43b28-5f6a-11e4-80ba-71d5fdeb905e.PNG)
[Figure 2, 3] I checked this problem in Windows Character Map and BabelMap respectively, this character has inadequate form in both applications.

**Comment by acuteaccent** [comment]
Another thought about this character just entered my head.

Well, one thing to keep in mind is that most end users don't care about the story (or etymology, sometimes) behind a certain character. People use characters just because they are actually needed, or just because they are in Unicode. And most type designers include glyphs for characters – including deprecated ones – just because they are there. For example, the character ŉ (U+0149 LATIN SMALL LETTER N PRECEDED BY APOSTROPHE) is officially deprecated and its use is strongly discouraged. But some people still use that character and a lot of type designers include glyphs for it. Why? Just because it is there.
For U+332C ㌬, the same approach can be taken – that is, include a glyph for it. (And people will no longer ask questions about why this character is not covered.)

**Comment by kenlunde** [comment]
U+332C is a ghost character, and while I considered mapping it to the originally intended ligature form of バーツ, that doesn't work due to its decomposition. At least for fonts for which I am responsible, U+332C shall remain blank.
