### ISSUE TITLE
Half-width '0' is confused with 'O'

### ISSUE THREAD

**Issue by Asvel** [adobe-fonts/source-han-sans#83]
The half-width '0' (Identity.63055)
![0](https://cloud.githubusercontent.com/assets/2691565/5556312/ac407018-8d12-11e4-998f-25c32b308063.png)

and the half-width 'O' (Identity.63086)
![o](https://cloud.githubusercontent.com/assets/2691565/5556317/c60dced2-8d12-11e4-93fa-9278b0c2124b.png)

By the way, is there a guide or tool about editing the binary parts in this project?

**Comment by acuteaccent** [comment]
By the way, the following two standardized variation sequences were added in Unicode 9.0.

0030 FE00; short diagonal stroke form; # DIGIT ZERO
2205 FE00; zero with long diagonal stroke overlay form; # EMPTY SET

**Comment by acuteaccent** [comment]
But just because there is no precedence does not mean you cannot do something different. You don't always necessarily have to follow the convention that is somehow established.
(In fact, there is a precedence (first version released in October 2008): https://github.com/naver/nanumfont/releases; https://github.com/naver/nanumfont/blob/master/README.md readme document in Korean)
