### ISSUE TITLE
Behaviour of SHS on Android

### ISSUE THREAD

**Issue by zzn2** [adobe-fonts/source-han-sans#88]
Android TextView with SHS resulted into strange displaying:

![device-2015-03-09-153116](https://cloud.githubusercontent.com/assets/113209/6551323/8d05b6ac-c671-11e4-9a15-7378fd5738d0.png)

I found the values `top`, `bottom`, `leading` in font metrics is far more bigger than the ones in Android default font. (but `ascent`, `descent` seems no problem.)

![device-2015-03-09-140441](https://cloud.githubusercontent.com/assets/113209/6551325/9856bfa6-c671-11e4-874f-9447a7548b99.png)

My question is 
1. What is the purpose for `top`, `bottom`, `leading` with a big value in SHS?
2. Can I modify these values somehow and rebuid the font so that it will display properly on Android TextView?
(Sorry for my pool English...)

**Comment by kenlunde** [comment]
There are two things happening here, one of which is planning to be changed for the forthcoming Version 1.002 update, and the other points to an issue in Android.

First, we already have plans to change the line gap value, as expressed in the 'OS/2', 'hhea', and 'vhea' tables, from 500 to 0 (zero) in the Version 1.002 update.

Second, the way that both examples are being used is different. Let me explain. The Android Default example is using font fallback whereby the equivalent Noto Sans CJK font is being referenced via the font fallback chain. The Latin font is the primary font, and that is where these so-called vertical metrics are coming from. In other words, the primary font in the font fallback chain is used to determine vertical metrics, which are inherited by (or forced upon) the other fonts in the font fallback chain. (Source Han Sans and Noto Sans CJK are 100% identical except for the names; I know, because I built both families at the same time.)

The issue in Android is that it is ignoring the ascent and descent values that are specified in the 'OS/2' table, which would be about 130 and 36, respectively, for your examples. Android is instead using the FontBBox (font bounding box) values, whose somewhat large values are caused by the mere presence of glyphs for the following characters: U+2E3A (vertical), U+2E3B (vertical), U+3031, and U+3032.

Of course, because you are using a version of Android that includes the Noto Sans CJK fonts, there is no reason to replace the fonts with the equivalent Source Han Sans versions, unless you prefer the Western glyphs in Source Han Sans / Noto Sans CJK that are being overridden by the primary font in the font fallback chain.

Anyway, I am keeping this issue open until the Version 1.002 update has been released.

**Comment by monokano** [comment]
![fontbbox_roboto](https://cloud.githubusercontent.com/assets/2377943/6567503/ac417bba-c70b-11e4-8b2f-0f3399abc183.png)
![fontbbox_shs](https://cloud.githubusercontent.com/assets/2377943/6567508/b1eb5946-c70b-11e4-9e18-b9e857efe9e5.png)
This rectangle of the blue line is FontBBox. 
FontBBox is no layout information. Android is used incorrectly it.

**Comment by kenlunde** [comment]
This Issue is good for referring Google in terms of illustrating poor font handling in their Android OS.

**Comment by behdad** [comment]
FontBBox shouldn't be relied on for pretty much anything.  If it's incorrect, that's fine IMO.

**Comment by behdad** [comment]
Humm.  It's not clear to me what the Android issue being discussed is.

**Comment by kenlunde** [comment]
@behdad: What @zzn2 is reporting suggests that Android OS uses the FontBBox of the primary font in the font fallback chain for vertical metrics, and applies that font's setting to all of the subsequent fonts in the font fallback chain.

**Comment by behdad** [comment]
I have a hard time imagining that.  @roozbehp, can you clarify?

@zzn2: what's the test program you are using?

**Comment by roozbehp** [comment]
I believe what Ken is saying in [his comment above](https://github.com/adobe-fonts/source-han-sans/issues/88#issuecomment-77845708) is correct. Android uses yMin and yMax of the first font in the fallback chain to determine the line spacing.

The reasons are historical, but hard to change since some apps now depend on it.

**Comment by behdad** [comment]
Thanks for the clarification.  That's, so broken :).  Anyway, I trust Raph has considered all the options...

**Comment by roozbehp** [comment]
@raphlinus FYI.

**Comment by raphlinus** [comment]
Agree with the above. It is indeed Android behavior to use yMin and yMax from the font bbox, I know this behavior is not ideal, however changing it would cause compatibility problems. I would like to revisit the issue, but just about anything we do is going to cause headaches of some kind.

**Comment by zzn2** [comment]
Thanks everyone!

I got a clear understanding of font bbox from [this blog post](http://tama-san.com/illustratorでsource-han-sansのバウンディングボックスが縦長になる/)  by @monokano, and understood how the values of font bbox in SHS are designed, by explanations from @kenlunde.

Also I got clarified the display result on TextView points to an issue in Android, as explained by @kenlunde @behdad @roozbehp @raphlinus. It's hard to change this behavior considering the compatibility problems...


> Android uses yMin and yMax of the first font in the fallback chain to determine the line spacing.

@behdad @roozbehp @raphlinus
Could you please tell me the code handling the fallback chain?
I'm wondering how Android handles with multiple fonts, and want to know if there could be some workaround for the TextView-not-displayed-properly problem from the App side.


> First, we already have plans to change the line gap value, as expressed in the 'OS/2', 'hhea', and 'vhea' tables, from 500 to 0 (zero) in the Version 1.002 update.
> Anyway, I am keeping this issue open until the Version 1.002 update has been released.

@kenlunde
Sure. Looking forward for the new release :)

> @zzn2: what's the test program you are using?

@behdad
The test program was a demo app written by me using Android's TextView and Canvas APIs.
The code snippet of drawing is something like [this](https://gist.github.com/zzn2/71d679c7e0185dbea445).

**Comment by zzn2** [comment]
@monokano Could you please tell me what software are you using to show the font's bbox as attached [here](https://github.com/adobe-fonts/source-han-sans/issues/88#issuecomment-77977029) ?

**Comment by monokano** [comment]
I used app made by myself. 
Gets font information uses the AFDKO.

**Comment by zzn2** [comment]
@monokano I see. Thanks :)

**Comment by ShikiSuen** [comment]
@kenlunde Will you Adobe let Google know this issue regarding what @monokano said?

**Comment by kenlunde** [comment]
Google is aware that there is an issue to fix in Android. (Also, I am on vacation this week. and didn't bring my computer.)

**Comment by kenlunde** [comment]
The behavior may be better with the Version 1.002 fonts, although Android OS still needs to be fixed.

**Comment by madig** [comment]
For future reference, Android provides newer APIs to set line-height:

https://android-developers.googleblog.com/2018/07/whats-new-for-text-in-android-p.html
https://developer.android.com/reference/android/widget/TextView.html#attr_android:lineHeight
https://developer.android.com/reference/android/widget/TextView.html#attr_android:firstBaselineToTopHeight
https://developer.android.com/reference/android/widget/TextView.html#attr_android:lastBaselineToBottomHeight

Devs should probably use them instead of relying on the font or hoping that base behavior changes.
