### ISSUE TITLE
Incorrect glyph 朌 (U+670C) and 肦 U+80A6 for TW version

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-sans#89]
As shown in the screenshot, 朌 U+670C and 肦 U+80A6 of the TW variant have some issues:

1. The radical of 朌 U+670C is 月, but it is using the 肉 component, so that it is mixed with 肦 U+80A6.

2. The CN version of 肦 (U+80A6) is used in TW, which causes the component 分 not consistent with other words having the same component (note the second stroke).

If the above observation is correct, the following adjustments could be made as a fix:

1. Replace 肦 (U+80A6) with the glyph of 朌 (U+670C) ;
2. Change 朌 (U+670C) to use the glyph same as that of JP or K version.

(BTW, also not sure if CN should distinguish these two radicals as in current version, as "Radical #130 should look like Radical #74" [1].)

[1] http://blogs.adobe.com/CCJKType/2014/11/gb-18030-oddity-or-design-flaw-redux.html

![twbug](https://cloud.githubusercontent.com/assets/959433/6763722/a6fdaca2-cfc4-11e4-9fd0-396deda2f480.png)

**Comment by kenlunde** [comment]
Why couldn't this have been submitted a couple of days ago? &#x263A;

(I wrote that because the Version 1.002 fonts were built on Wednesday evening, and are now going through testing. While this is a trivial fix to one CMap resource, it is a big crank, so unless another issue is found during testing that necessitates a rebuild, this trivial fix may need to wait until the next update.)

This is a bug. The glyph, uni670C-HK (CID+21097), is now earmarked for removal, and the mapping for U+670C in the TW CMap resource (and that for the experimental HK CMap resource, when I find the time to make it) will be changed to uni670C-JP (CID+21095) per your suggestion.

If I am able to squeeze this trivial fix in the Version 1.002 update, it will be noted here, and in the "Changes" section of the ReadMe PDF.

**Comment by tamcy** [comment]
Unfortunately I discovered this problem this morning ;)

Do you have any comment on the glyph of U+80A6 (for TW and CN)?

**Comment by kenlunde** [comment]
Yes, the top of the right side of the TW glyph for U+80A6 needs to be adjusted (actually, it will require a completely new glyph, which will be named uni80A6-HK), but the CN glyph for the same character is actually okay, or at least intended, based on the GB 18030 standard. See [this article](http://blogs.adobe.com/CCJKType/2014/01/gb-18030-oddity-or-design-flaw.html) for the details and my analysis. I also wrote a [followup article](http://blogs.adobe.com/CCJKType/2014/11/gb-18030-oddity-or-design-flaw-redux.html) on this subject (be sure to read my comment at the very end).

**Comment by tamcy** [comment]
Thanks for the info. So basically it "resurrected" the traditional style of 肉 radical in some of the glyphs with 肦 being one of them.

**Comment by kenlunde** [comment]
While I am not sure whether "resurrected" is the most accurate way to describe this phenomenon, I would summarize the situation by stating that if a character that uses Radical 130 as its left-side component is in G0, G1, or G3 (and possibly G5), it should use the Radical 74 form, and otherwise should look distinct by using the Radical 130 form only when a corresponding character that uses Radical 74 is encoded. (This means that the form of U+813C that I pointed out in the [original article](http://blogs.adobe.com/CCJKType/2014/01/gb-18030-oddity-or-design-flaw.html) is intentional.)

**Comment by kenlunde** [comment]
Consolidated with Issue #99.
