### ISSUE TITLE
(Question) Why does the glyph of u5220 look the same as u522A in TW?

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-sans#92]
![522ab](https://cloud.githubusercontent.com/assets/959433/6795678/49e46562-d21f-11e4-8d7a-7dc8841a1103.png)

There should be no doubt that in practice 冊 (u518A) is a variant of 册 (u518c). In Unicode, separate codepoints are assigned for these two characters, and so are some (if not all) of the compound characters using the said components.

So 刪 (u522A) is formed by 冊 (u518A) +刂 ; while 删 (u5220) is formed by 册 (518C) +刂.

Source Han Sans TW uses different glyphs for 冊 and 册. Also true for 柵 and 栅. However, I found that it is using the same glyph for 删 (u5220), making it the same as 刪 (u522A). I believe the glyph of 刪 (u5220), which falls within the Big5 range, is correct. In this case, I am not sure if the behavior of 删 (u5220) in TW is intended. Since it isn't in the Big5 range, I can't see why the standard body would make it identical to the one in other codepoint, and I am inclined to believe it should behave like in JP/KR/CN. But I don't have enough evidence to regard this as a bug, so I am asking here. Thanks.

**Comment by kenlunde** [comment]
The initial HK coverage is left intact for the current TW fonts, which is why. Dealing with this is within the scope of properly handling HK via separate fonts and font instances. Note that U+5220 is outside the scope of Big Five proper, and is treated as an HK character. Still, the form is incorrect, and the fix will be to map U+5220 to uni5220-CN for the TW fonts, which means that all four languages will share the same glyph.

**Comment by extc** [comment]
For your information:
Taiwan has the character「 册刂」in rare character category(罕用字), T3-2461.
![t3-2461](https://cloud.githubusercontent.com/assets/8214015/6881245/f74860d0-d591-11e4-9eb7-1e2cfe984dbb.JPG) 

while Hong Kong has the character 「 册刂」in initial HKSCS (now known as HKSCS-1999)
![chkscs99](https://cloud.githubusercontent.com/assets/8214015/6881249/1b5f7544-d592-11e4-86c7-ce091b137191.JPG)
Both mapped to U+5220

In Lexical Lists for Chinese Learning in Hong Kong(香港小學學習字詞表), 删 is shown as the variant character of 刪. It has slight stoke difference with the register in the above standard -- first stroke being vertical stroke instead of 撇筆.
![lexlist_ch](https://cloud.githubusercontent.com/assets/8214015/6881278/2ccc1fb6-d593-11e4-8c1f-c69bb3b85c92.JPG)

**Comment by kenlunde** [comment]
Consolidated with Issue #98.
