### ISSUE TITLE
Inconsistent shape for 原(U+539F) and 原(U+539F) as component of some glyphs (Simplified Chinese)

### ISSUE THREAD

**Issue by fatloong** [adobe-fonts/source-han-sans#96]
In glyphs 原(U+539F), 源(U+6E90), 愿(U+613F), 塬(U+586C), the first stroke(丿) of component "白" is separated from the first stroke(一) of component "厂". However in glyph 嫄(U+5AC4), 願(U+9858), 羱(U+7FB1), the first stroke(丿)  of component "白" is connected to the first stroke(一) of component "厂". It looks like that 原, 源, 愿, 塬 and 嫄, 願, 羱 have different style although they share a same component "原". I wonder whether it is a font bug or not.
![sourcehansanssc-1](https://cloud.githubusercontent.com/assets/11400000/7114516/9006d894-e210-11e4-971f-0f88e91ee13c.png)

I have compared fonts of Microsoft Yahei and Hiragino Sans GB, and found that component "原" has consistent shape for these glyphs and the first stroke(丿) of component "白" is linked to the first stroke(一) of component "厂" in all of these glyphs. 
![microsoftyahei-2](https://cloud.githubusercontent.com/assets/11400000/7114521/9dc39a26-e210-11e4-9b6c-8ee4d7619cce.png)
![hiraginogb-3](https://cloud.githubusercontent.com/assets/11400000/7114523/a8abd73c-e210-11e4-8817-50adbbffca82.png)

**Comment by ShikiSuen** [comment]
Only those glyphs only used in Simplified Chinese will follow GB18030 standards, others may follow either CNS11643 or JIS depends on your font fallback settings or what kind of release are you using.

**Comment by ShikiSuen** [comment]
I removed my last reply and replace it with the following one:

In a general manner, only those glyphs defined in GB18030 will follow GB18030 standards, others may follow either CNS11643 or JIS depends on your font fallback settings or on what kind of release are you using.

But, What I have seen are the following:
![font](https://cloud.githubusercontent.com/assets/3164826/7121202/07fe53a4-e1d0-11e4-9058-5986e1b10f5f.png)

Thus, my conclusion is that the TC version of SHS still hadn't follow CNS11643 thoroughly, and so did the SC version of SHS 1.001.

**Comment by tamcy** [comment]
1. I first thought that this kind of subtle difference (whether to disjoint the first stroke of 白 from the top stroke 一 of 厂) should be a design decision of individual fonts but not something about standard adherence. Strangely such inconsistency exists in various fonts, but the implementation could be different. In SHS(TC), 原源愿塬 is one group, 願羱 is another , while in MingLi, 愿 falls into the group having 願羱.  I am also interested to know why :)

2. On the other hand, TC's 愿 looks incorrect to me - the 丿 stroke should not extend to the left of the lower component 心. It should look like KR and JP, just without the hook.

3. Off-topic, I know. But seeing the words in the screenshot, 羱 immediately comes to my attention because the balance of the two components don't look quite right to me.

**Comment by kenlunde** [comment]
The next major version, which will be after Version 1.002, will include a rather large number of tweaks, whose aim is to address issues such as this one.

I may open a new Issue whose purpose is to consolidate such glyphs into a single Issue for better tracking.

**Comment by kenlunde** [comment]
Consolidated with Issue #99.
